export const ar = {
  'common.back': 'رجوع',
  'common.cancel': 'إلغاء',
  'common.close': 'إغلاق',
  'common.continue': 'متابعة',
  'common.delete': 'حذف',
  'common.decrease': 'تقليل',
  'common.done': 'تم',
  'common.edit': 'تعديل',
  'common.error': 'صار خطأ',
  'common.goToSettings': 'الذهاب للإعدادات',
  'common.loading': 'جاري التحميل…',
  'common.later': 'لاحقًا',
  'common.increase': 'زيادة',
  'common.next': 'التالي',
  'common.notAvailable': 'غير متاح',
  'common.retry': 'حاول مرة ثانية',
  'common.save': 'حفظ',
  'common.saving': 'جاري الحفظ…',

  'fasting.title': 'الصيام',
  'fasting.badge': 'صيام',
  'fasting.openDetails': 'فتح تفاصيل الصيام',
  'fasting.viewDetails': 'عرض التفاصيل',
  'fasting.goalRemaining': 'باقي {{remaining}} على هدف {{hours}}',
  'fasting.goalReached': 'وصلت للهدف · {{hours}}',
  'fasting.elapsed': 'مضى {{elapsed}}',
  'fasting.ready': 'جاهز تبدأ؟',
  'fasting.startFast': 'ابدأ الصيام',
  'fasting.startAccessibility': 'بدء صيام',
  'fasting.lastFast': 'آخر صيام {{duration}}',
  'fasting.lastFastWithDate': 'آخر صيام {{duration}} · {{date}}',
  'fasting.startTitle': 'ابدأ صيامك',
  'fasting.customHours': 'مدة الصيام بالساعات',
  'fasting.hourUnit': 'ساعة',
  'fasting.startTime': 'وقت البداية',
  'fasting.starting': 'جاري البدء…',
  'fasting.started': 'بدأ الصيام',
  'fasting.startFailed': 'ما قدرنا نبدأ الصيام',
  'fasting.selectProtocol': 'اختيار {{protocol}}',
  'fasting.protocol': 'نظام الصيام',
  'fasting.protocolPill': 'نظام {{protocol}}',
  'fasting.protocolWithDuration': '{{protocol}} · صيام {{duration}}',
  'fasting.timeLeft': '{{percent}}٪ · باقي {{remaining}}',
  'fasting.goalComplete': 'وصلت للهدف',
  'fasting.average': 'المتوسط',
  'fasting.count': 'عدد المرات',
  'fasting.total': 'الإجمالي',
  'fasting.startedAt': 'بدأ',
  'fasting.goalAt': 'موعد الهدف',
  'fasting.endFast': 'إنهاء الصيام',
  'fasting.noActiveTitle': 'ما عندك صيام حالي',
  'fasting.noActiveDescription': 'ابدأ صيامك وتابع مدته ومراحله من مكان واحد.',
  'fasting.metabolicStages': 'مراحل الصيام',
  'fasting.currentStage': 'الآن',
  'fasting.endTitle': 'إنهاء الصيام',
  'fasting.fastedDuration': 'مدة الصيام: {{duration}}',
  'fasting.endedAt': 'انتهى',
  'fasting.invalidTime': 'لازم يكون وقت البداية قبل وقت النهاية.',
  'fasting.ending': 'جاري الإنهاء…',
  'fasting.ended': 'تم إنهاء الصيام',
  'fasting.endFailed': 'ما قدرنا ننهي الصيام',

  'errors.unexpectedTitle': 'صار خطأ',
  'errors.unexpectedDescription':
    'صار خطأ غير متوقع. جرّب مرة ثانية، وإذا استمر تأكد إن التطبيق والخادم محدثين.',
  'errors.sectionFailed': 'ما قدرنا نحمّل هالقسم.',

  'notifications.workoutChannel': 'مؤقت التمرين',
  'notifications.fastingChannel': 'الصيام',
  'notifications.offTitle': 'التنبيهات مقفلة',
  'notifications.offDescription': 'المؤقت بيظل ينبهك داخل التطبيق.',
  'notifications.restComplete': 'خلص وقت الراحة',
  'notifications.restNextSet': 'خلصت الراحة — جهّز للمجموعة الجاية',
  'notifications.restBody': '{{exercise}} · المجموعة {{set}} من {{total}}',
  'notifications.restTarget': '{{body}} · الهدف {{reps}}',
  'notifications.fastingGoalTitle': 'وصلت لهدف الصيام',
  'notifications.fastingGoalBody': 'أكملت هدفك، عساك على القوة!',

  'appSettings.theme': 'المظهر',
  'appSettings.themeLight': 'فاتح',
  'appSettings.themeDark': 'داكن',
  'appSettings.themeAmoled': 'أسود AMOLED',
  'appSettings.themeSystem': 'حسب الجهاز',
  'appSettings.liquidGlass': 'التنقل بالزجاج السائل',
  'appSettings.liquidGlassDescription':
    'استخدم شريط التبويب ورؤوس الشاشات بتصميم iOS 26.',
  'appSettings.notifications': 'التنبيهات',
  'appSettings.notificationsDescription': 'تنبيهات راحة التمرين وأهداف الصيام.',
  'appSettings.haptics': 'الاستجابة اللمسية',
  'appSettings.hapticsDescription': 'اهتزازات خفيفة للمؤقتات وتأكيد الإجراءات.',
  'appSettings.cameraSound': 'صوت الكاميرا',
  'appSettings.cameraSoundDescription': 'شغّل صوتًا عند التقاط الصور.',

  'dashboardSettings.askSparky': 'اسأل سباركي',
  'dashboardSettings.askSparkyDescription':
    'إظهار اختصار اسأل سباركي في الرئيسية.',
  'dashboardSettings.hydration': 'شرب الماء',
  'dashboardSettings.hydrationDescription':
    'إظهار بطاقة شرب الماء في الرئيسية.',
  'dashboardSettings.fasting': 'الصيام',
  'dashboardSettings.fastingDescription': 'إظهار بطاقة الصيام في الرئيسية.',
  'dashboardSettings.customNutrients': 'العناصر الغذائية المخصصة',
  'dashboardSettings.noCustomNutrients': 'ما عندك عناصر غذائية مخصصة',
  'dashboardSettings.noCustomNutrientsDescription':
    'أنشئ عناصر غذائية مخصصة من نسخة الويب، وبعدها اختر هنا وش يظهر في الرئيسية.',
  'dashboardSettings.noServerTitle': 'ما فيه خادم مربوط',
  'dashboardSettings.noServerDescription':
    'اربط خادمك من الإعدادات عشان تختار العناصر الغذائية المخصصة.',
  'dashboardSettings.updateFailed': 'ما قدرنا نحدّث الإعداد.',
  'dashboardSettings.showCustomNutrient': 'إظهار {{nutrient}} في الرئيسية',

  'tabs.dashboard': 'الرئيسية',
  'tabs.diary': 'اليوميات',
  'tabs.add': 'إضافة',
  'tabs.library': 'المكتبة',
  'tabs.settings': 'الإعدادات',

  'addSheet.food': 'صنف غذائي',
  'addSheet.exercise': 'تمرين',
  'addSheet.measurements': 'القياسات',
  'addSheet.scanFood': 'مسح منتج',
  'addSheet.workout': 'تمرين مباشر',
  'addSheet.workoutSubtitle': 'مجموعات وتكرارات مباشرة',
  'addSheet.activity': 'نشاط',
  'addSheet.activitySubtitle': 'مدة ومسافة',
  'addSheet.logWorkout': 'تسجيل تمرين سابق',
  'addSheet.logWorkoutSubtitle': 'مجموعات وتكرارات سابقة',
  'addSheet.askSparky': 'اسأل سباركي',
  'addSheet.syncHealth': 'مزامنة البيانات الصحية',

  'alerts.noServerTitle': 'ما فيه خادم متصل',
  'alerts.addExerciseNeedsServer': 'اربط خادمك من الإعدادات عشان تضيف تمرينًا.',
  'alerts.startWorkoutNeedsServer':
    'اربط خادمك من الإعدادات عشان تبدأ تمرينًا.',
  'alerts.draftTitle': 'عندك مسودة',
  'alerts.unsavedDraft': 'عندك مسودة {{activityType}} ما حفظتها. وش تبي تسوي؟',
  'alerts.workout': 'تمرين',
  'alerts.activity': 'نشاط',
  'alerts.resumeDraft': 'متابعة المسودة',
  'alerts.discardAndContinue': 'حذف المسودة والمتابعة',
  'alerts.healthUnavailableTitle': 'البيانات الصحية غير متاحة',
  'alerts.healthUnavailableDescription':
    'تعذر الوصول للبيانات الصحية. تأكد من الصلاحيات في الإعدادات.',

  'library.noServerTitle': 'ما فيه خادم مربوط',
  'library.noServerDescription': 'اربط خادمك من الإعدادات عشان تشوف مكتبتك.',
  'library.loading': 'جاري تحميل المكتبة…',
  'library.create': 'إنشاء جديد',
  'library.browse': 'استعراض المكتبة',
  'library.food': 'صنف غذائي',
  'library.meal': 'وجبة',
  'library.exercise': 'تمرين',
  'library.workoutPreset': 'قالب تمرين',
  'library.manualEntry': 'إضافة يدوية',
  'library.groupFoods': 'اجمع أصنافك في وجبة',
  'library.exerciseRoutine': 'رتّب تمارينك واحفظها',
  'library.foods': 'الأصناف الغذائية',
  'library.meals': 'الوجبات',
  'library.exercises': 'التمارين',
  'library.workoutPresets': 'قوالب التمرين',
  'library.recentlyLogged': 'المسجّل مؤخرًا',
  'library.loadingRecent': 'جاري تحميل آخر تسجيلاتك…',
  'library.recentError': 'ما قدرنا نحمّل آخر تسجيلاتك.',
  'library.emptyTitle': 'ما سجّلت شي للحين',
  'library.emptyDescription':
    'الأصناف والوجبات والتمارين اللي تسجلها بتطلع هنا عشان توصل لها بسرعة.',
  'library.connectionError': 'تأكد من اتصالك وحاول مرة ثانية.',
  'library.tryAnotherSearch': 'جرّب كلمة بحث ثانية.',
  'library.searchFoods': 'ابحث في الأصناف الغذائية…',
  'library.noFoods': 'ما عندك أصناف غذائية للحين',
  'library.noMatchingFoods': 'ما لقينا أصناف تطابق بحثك',
  'library.savedFoodsAppear': 'الأصناف اللي تحفظها أو تسجلها بتظهر هنا.',
  'library.loadingFoods': 'جاري تحميل الأصناف الغذائية…',
  'library.loadFoodsFailed': 'ما قدرنا نحمّل الأصناف الغذائية',
  'library.loadMoreFoodsFailed': 'ما قدرنا نحمّل أصناف أكثر.',
  'library.searchMeals': 'ابحث في الوجبات…',
  'library.noMeals': 'ما عندك وجبات للحين',
  'library.noMatchingMeals': 'ما لقينا وجبات تطابق بحثك',
  'library.savedMealsAppear': 'الوجبات اللي تنشئها بتظهر هنا.',
  'library.loadingMeals': 'جاري تحميل الوجبات…',
  'library.searchMealsFailed': 'ما قدرنا نبحث في الوجبات',
  'library.loadMealsFailed': 'ما قدرنا نحمّل الوجبات',
  'library.searchExercises': 'ابحث في التمارين…',
  'library.noExercises': 'ما عندك تمارين للحين',
  'library.noMatchingExercises': 'ما لقينا تمارين تطابق بحثك',
  'library.savedExercisesAppear': 'التمارين اللي تحفظها أو تسجلها بتظهر هنا.',
  'library.loadingExercises': 'جاري تحميل التمارين…',
  'library.loadExercisesFailed': 'ما قدرنا نحمّل التمارين',
  'library.loadMoreExercisesFailed': 'ما قدرنا نحمّل تمارين أكثر.',
  'library.searchWorkoutPresets': 'ابحث في قوالب التمرين…',
  'library.noWorkoutPresets': 'ما عندك قوالب تمرين للحين',
  'library.noMatchingWorkoutPresets': 'ما لقينا قوالب تطابق بحثك',
  'library.savedWorkoutPresetsAppear': 'قوالب التمرين اللي تنشئها بتظهر هنا.',
  'library.loadingWorkoutPresets': 'جاري تحميل قوالب التمرين…',
  'library.loadWorkoutPresetsFailed': 'ما قدرنا نحمّل قوالب التمرين',
  'library.loadMoreWorkoutPresetsFailed': 'ما قدرنا نحمّل قوالب أكثر.',

  'exerciseSearch.saved': 'المحفوظة',
  'exerciseSearch.online': 'عبر الإنترنت',
  'exerciseSearch.addFailed': 'ما قدرنا نضيف التمرين',
  'exerciseSearch.searchFailed': 'ما قدرنا نبحث في التمارين',
  'exerciseSearch.recent': 'المستخدمة مؤخرًا',
  'exerciseSearch.popular': 'الأكثر استخدامًا',
  'exerciseSearch.connectToView': 'اربط خادمك عشان تشوف تمارينك.',
  'exerciseSearch.startPrompt': 'ابحث عن تمرين عشان تبدأ.',
  'exerciseSearch.loadMoreFailed':
    'ما قدرنا نحمّل المزيد. اضغط للمحاولة مرة ثانية',
  'exerciseSearch.loadMore': 'تحميل المزيد',
  'exerciseSearch.providerSearchFailed': 'ما قدرنا نبحث في {{provider}}',
  'exerciseSearch.connectOnline':
    'اربط خادمك عشان تبحث عن تمارين عبر الإنترنت.',
  'exerciseSearch.providersFailed': 'ما قدرنا نحمّل مصادر التمارين',
  'exerciseSearch.noProviders': 'ما فيه مصادر تمارين عبر الإنترنت مضافة',
  'exerciseSearch.searchProvider': 'ابحث في {{provider}} عن تمرين',
  'exerciseSearch.clearSearch': 'مسح البحث',
  'exerciseSearch.selectProvider': 'اختيار مصدر {{provider}}',
  'exerciseSearch.addExercise': 'إضافة {{exercise}}',

  'presetSearch.searchFailed': 'ما قدرنا نبحث في قوالب التمرين',
  'presetSearch.noMatches': 'ما لقينا قوالب تطابق بحثك',
  'presetSearch.loadFailed': 'ما قدرنا نحمّل قوالب التمرين',
  'presetSearch.noPresets': 'ما عندك قوالب تمرين للحين',
  'presetSearch.noPresetsDescription':
    'ابدأ من الصفر، أو احفظ تمرينك كقالب وبيظهر هنا.',
  'presetSearch.searchPlaceholder': 'ابحث في القوالب…',
  'presetSearch.startFromScratch': 'ابدأ من الصفر',
  'presetSearch.pickFirstExercise': 'اختر أول تمرين',

  'foodSearch.allSources': 'جميع المصادر',
  'foodSearch.detailsUnavailable': 'التفاصيل غير متاحة',
  'foodSearch.partialDetails': 'فتحنا البيانات المتاحة؛ راجعها قبل الحفظ.',
  'foodSearch.recentlyLogged': 'المسجّل مؤخرًا',
  'foodSearch.topFoods': 'الأكثر تسجيلًا',
  'foodSearch.yourFoods': 'أصنافك',
  'foodSearch.yourMeals': 'وجباتك',
  'foodSearch.topMatches': 'أفضل النتائج',
  'foodSearch.bySource': 'حسب المصدر',
  'foodSearch.noSavedFoods': 'ما لقينا أصناف محفوظة',
  'foodSearch.noSavedFoodsOrMeals': 'ما لقينا أصناف أو وجبات محفوظة',
  'foodSearch.searchingSavedFoods': 'جاري البحث في أصنافك المحفوظة',
  'foodSearch.searchingSavedFoodsAndMeals':
    'جاري البحث في أصنافك ووجباتك المحفوظة',
  'foodSearch.onlineResults': 'نتائج الإنترنت',
  'foodSearch.onlineProvider': 'مصدر النتائج',
  'foodSearch.sourceChange': 'المصدر {{source}}؛ اضغط للتغيير',
  'foodSearch.providerLoadFailed':
    '{{provider}}، تعذّر التحميل. اضغط للمحاولة مرة ثانية',
  'foodSearch.providerNoResults': '{{provider}}، ما فيه نتائج',
  'foodSearch.providerResults':
    '{{provider}}، {{count}} نتيجة. اضغط لـ{{action}}',
  'foodSearch.expand': 'التوسيع',
  'foodSearch.collapse': 'الطي',
  'foodSearch.couldNotLoad': 'تعذّر التحميل',
  'foodSearch.noResults': 'ما فيه نتائج',
  'foodSearch.showAllProvider': 'عرض كل نتائج {{provider}} ({{count}})',
  'foodSearch.showAllFoods': 'عرض كل الأصناف ({{count}})',
  'foodSearch.showAllMeals': 'عرض كل الوجبات ({{count}})',
  'foodSearch.loadMoreFailed': 'ما قدرنا نحمّل المزيد. اضغط للمحاولة مرة ثانية',
  'foodSearch.loadMore': 'تحميل المزيد',
  'foodSearch.noOnlineResults': 'ما فيه نتائج من {{provider}}',
  'foodSearch.searchPlaceholder': 'ابحث عن صنف أو وجبة…',
  'foodSearch.clearSearch': 'مسح البحث',
  'foodSearch.scanFood': 'مسح منتج',
  'foodSearch.addFood': 'إضافة صنف غذائي',
  'foodSearch.addFoodOrMeal': 'إضافة صنف أو وجبة',
  'foodSearch.connectServer': 'اربط خادمك عشان تبحث في الأصناف.',
  'foodSearch.loadFailed': 'ما قدرنا نحمّل الأصناف الغذائية',
  'foodSearch.startPrompt': 'ابحث عن صنف أو وجبة وسجّلها.',
  'foodSearch.newFood': 'صنف غذائي جديد',
  'foodSearch.newMeal': 'وجبة جديدة',
  'foodSearch.introTitle': 'كل النتائج في بحث واحد',
  'foodSearch.introDescription':
    'أصنافك ووجباتك والنتائج من الإنترنت تظهر مع بعض وأنت تكتب.',
  'foodSearch.sourceTitle': 'اختر المصدر',
  'foodSearch.sourceDescription':
    'من هنا تبدّل المصدر أو تبحث في جميع المصادر.',

  'foodEntry.adjustNutrition': 'تعديل القيم الغذائية',
  'foodEntry.saveFood': 'حفظ الصنف',
  'foodEntry.selectServing': 'اختيار الحصة',
  'foodEntry.date': 'التاريخ',
  'foodEntry.useToday': 'استخدم اليوم',
  'foodEntry.meal': 'الوجبة',
  'foodEntry.selectMeal': 'اختيار الوجبة',
  'foodEntry.addFood': 'إضافة الصنف',
  'foodEntry.addMeal': 'إضافة الوجبة',
  'foodEntry.saveChanges': 'حفظ تغييرات التسجيل الغذائي',
  'foodEntry.editEntry': 'تعديل التسجيل الغذائي',
  'foodEntry.tapToEditNutrition': 'اضغط لتعديل القيم الغذائية',
  'foodEntry.deleting': 'جاري الحذف…',
  'foodEntry.deleteEntry': 'حذف التسجيل',
  'foodEntry.equivalentUnitsSaveFailed': 'ما قدرنا نحفظ بعض الوحدات المكافئة',
  'foodEntry.invalidAmount': 'الكمية غير صحيحة',
  'foodEntry.amountPositive': 'لازم تكون الكمية أكبر من صفر.',
  'foodEntry.addFoodFailed': 'ما قدرنا نضيف الصنف',
  'foodEntry.saveFoodFailed': 'ما قدرنا نحفظ الصنف',
  'foodEntry.addMealFailed': 'ما قدرنا نضيف الوجبة',
  'foodEntry.mealBuilderUnsupported': 'ما تقدر تضيف وجبة هنا',
  'foodEntry.selectFoodInstead': 'اختر صنفًا غذائيًا بدل وجبة ثانية.',
  'foodEntry.savedWithoutUnit': 'حفظنا الصنف بدون الوحدة الجديدة',
  'foodEntry.savedWithoutUnitDescription':
    'تقدر تضيف الصنف الآن، وبعدها جرّب تحفظ الوحدة مرة ثانية.',
  'foodEntry.perServing': '{{amount}} لكل حصة',
  'foodEntry.mealYield': 'تكفي {{servings}}',
  'foodEntry.serving.one': 'حصة واحدة',
  'foodEntry.serving.two': 'حصتين',
  'foodEntry.serving.few': '{{count}} حصص',
  'foodEntry.serving.other': '{{count}} حصة',

  'foodDetail.noServerTitle': 'ما فيه خادم مربوط',
  'foodDetail.noServerDescription':
    'اربط خادمك من الإعدادات عشان تشوف تفاصيل الصنف.',
  'foodDetail.editFood': 'تعديل الصنف الغذائي',
  'foodDetail.serving': 'الحصة',
  'foodDetail.servingOptions': 'خيارات الحصة',
  'foodDetail.loadingServingOptions': 'جاري تحميل خيارات الحصة…',
  'foodDetail.servingOptionsPartial': 'ما قدرنا نحمّل بعض خيارات الحصة الحين.',
  'foodDetail.barcode': 'الباركود',
  'foodDetail.notSet': 'غير مضاف',
  'foodDetail.logFood': 'تسجيل الصنف',
  'foodDetail.deleting': 'جاري الحذف…',
  'foodDetail.deleteFood': 'حذف الصنف',

  'mealDetail.perServing': 'لكل حصة',
  'mealDetail.total': 'الإجمالي',
  'mealDetail.editMeal': 'تعديل الوجبة',
  'mealDetail.noServerTitle': 'ما فيه خادم مربوط',
  'mealDetail.noServerDescription':
    'اربط خادمك من الإعدادات عشان تشوف تفاصيل الوجبة.',
  'mealDetail.loading': 'جاري تحميل الوجبة…',
  'mealDetail.loadFailed': 'ما قدرنا نحمّل الوجبة',
  'mealDetail.loadFailedDescription': 'تأكد من اتصالك وحاول مرة ثانية.',
  'mealDetail.yieldSummary': 'تكفي {{servings}} · {{ingredients}}',
  'mealDetail.foods': 'مكوّنات الوجبة',
  'mealDetail.linkedMeal': 'وجبة مرتبطة',
  'mealDetail.viewLinkedMeal': 'فتح الوجبة المرتبطة {{name}}',
  'mealDetail.macros':
    '{{protein}} بروتين · {{carbs}} كربوهيدرات · {{fat}} دهون',
  'mealDetail.logMeal': 'تسجيل الوجبة',
  'mealDetail.deleting': 'جاري الحذف…',
  'mealDetail.deleteMeal': 'حذف الوجبة',
  'mealDetail.ingredient.one': 'مكوّن واحد',
  'mealDetail.ingredient.two': 'مكوّنين',
  'mealDetail.ingredient.few': '{{count}} مكوّنات',
  'mealDetail.ingredient.other': '{{count}} مكوّن',

  'mealAdd.createMeal': 'إنشاء وجبة',
  'mealAdd.editMeal': 'تعديل الوجبة',
  'mealAdd.linkedMeal': 'وجبة مرتبطة',
  'mealAdd.editLinkedMealWeb':
    'تعديل مكوّنات الوجبة المرتبطة متاح حاليًا من نسخة الويب.',
  'mealAdd.foodFallback': 'صنف غذائي',
  'mealAdd.editIngredient': 'تعديل {{name}}',
  'mealAdd.removeIngredient': 'حذف {{name}}',
  'mealAdd.missingMealName': 'اسم الوجبة ناقص',
  'mealAdd.enterMealName': 'اكتب اسمًا للوجبة.',
  'mealAdd.invalidServingSize': 'حجم الحصة غير صحيح',
  'mealAdd.servingSizePositive': 'لازم يكون حجم الحصة أكبر من صفر.',
  'mealAdd.invalidTotalServings': 'عدد الحصص غير صحيح',
  'mealAdd.totalServingsPositive': 'لازم يكون عدد الحصص أكبر من صفر.',
  'mealAdd.invalidTotalAmount': 'الكمية الإجمالية غير صحيحة',
  'mealAdd.totalAmountPositive': 'لازم تكون الكمية الإجمالية أكبر من صفر.',
  'mealAdd.noIngredients': 'الوجبة بدون مكوّنات',
  'mealAdd.addIngredientFirst':
    'أضف صنفًا غذائيًا واحدًا على الأقل قبل الحفظ.',
  'mealAdd.missingIngredientData': 'بيانات أحد المكوّنات ناقصة',
  'mealAdd.readdIngredient':
    'أحد الأصناف ما له حصة محفوظة. احذفه وأضفه من جديد.',
  'mealAdd.mealName': 'اسم الوجبة *',
  'mealAdd.mealNamePlaceholder': 'مثال: كبسة دجاج',
  'mealAdd.description': 'الوصف (اختياري)',
  'mealAdd.descriptionPlaceholder': 'ملاحظات عن الوجبة',
  'mealAdd.totalServings': 'عدد الحصص *',
  'mealAdd.totalAmount': 'الكمية الإجمالية ({{unit}}) *',
  'mealAdd.unit': 'الوحدة',
  'mealAdd.selectUnit': 'اختيار الوحدة',
  'mealAdd.servingSize': 'حجم الحصة ({{unit}}) *',
  'mealAdd.foods': 'مكوّنات الوجبة',
  'mealAdd.addFood': 'إضافة صنف غذائي',
  'mealAdd.mealTotal': 'إجمالي الوجبة',
  'mealAdd.macros':
    '{{protein}} بروتين · {{carbs}} كربوهيدرات · {{fat}} دهون',

  'editLoggedMeal.mealName': 'اسم الوجبة',
  'editLoggedMeal.servings': 'عدد الحصص',
  'editLoggedMeal.foods': 'مكوّنات هالوجبة',
  'editLoggedMeal.noFoods': 'ما فيه أصناف في هالوجبة للحين.',
  'editLoggedMeal.addFood': 'إضافة صنف غذائي',
  'editLoggedMeal.saveMeal': 'حفظ الوجبة',
  'editLoggedMeal.loadFailed': 'ما قدرنا نحمّل الوجبة',
  'editLoggedMeal.updateFailed': 'ما قدرنا نحفظ الوجبة',
  'editLoggedMeal.noPermission': 'ما عندك صلاحية تعدّل هالوجبة.',

  'ingredientRow.removeTitle': 'حذف {{name}}؟',
  'ingredientRow.lastIngredientDescription':
    'هذا آخر مكوّن. أضف مكوّنًا ثانيًا قبل الحفظ، أو احذف الوجبة كاملة.',
  'ingredientRow.editIngredient': 'تعديل {{name}}',

  'foodPhoto.introTitle': 'قدّر القيم الغذائية من صورة',
  'foodPhoto.introDescription':
    'حوّل صورة وجبتك إلى تقدير غذائي تقدر تراجعه وتعدّله.',
  'foodPhoto.weightTitle': 'تعرف وزن الوجبة؟ أضفه',
  'foodPhoto.weightDescription':
    'الوزن الإجمالي يساعد على تقدير الحصص والسعرات والماكروز بدقة أفضل.',
  'foodPhoto.descriptionTitle': 'اكتب وصفًا بسيطًا',
  'foodPhoto.descriptionDescription':
    'اذكر الصوص والزيت والإضافات واسم المطعم، وأي مكوّن ما يبان بالصورة.',
  'foodPhoto.reviewTitle': 'راجع قبل الحفظ',
  'foodPhoto.reviewDescription':
    'التقدير نقطة بداية؛ تقدر تعدّل كل التفاصيل قبل ما تسجّل الوجبة.',
  'foodPhoto.logManually': 'أفضّل التسجيل اليدوي',
  'foodPhoto.improveTitle': 'حسّن التقدير',
  'foodPhoto.readingPhoto': 'جاري قراءة الصورة…',
  'foodPhoto.readingPhotos': 'جاري قراءة الصور…',
  'foodPhoto.identifyingIngredients': 'جاري تحديد المكوّنات…',
  'foodPhoto.estimatingPortions': 'جاري تقدير الكميات…',
  'foodPhoto.calculatingNutrition': 'جاري حساب القيم الغذائية…',
  'foodPhoto.almostThere': 'قربنا نخلص…',
  'foodPhoto.cameraPermissionTitle': 'نحتاج إذن الكاميرا',
  'foodPhoto.cameraPermissionDescription':
    'فعّل إذن الكاميرا عشان تضيف صورة.',
  'foodPhoto.takePhotoFailed': 'ما قدرنا نلتقط الصورة',
  'foodPhoto.loadPhotoFailed': 'ما قدرنا نحمّل الصورة',
  'foodPhoto.invalidWeight': 'الوزن غير صحيح',
  'foodPhoto.weightPositive': 'لازم يكون الوزن الإجمالي رقمًا أكبر من صفر.',
  'foodPhoto.descriptionTooLong': 'الوصف طويل',
  'foodPhoto.descriptionLimit': 'خل الوصف أقل من {{count}} حرف.',
  'foodPhoto.noImages': 'ما فيه صور',
  'foodPhoto.addImageFirst': 'أضف صورة واحدة على الأقل عشان ننشئ التقدير.',
  'foodPhoto.readPhotoFailed': 'ما قدرنا نقرأ الصورة',
  'foodPhoto.retakeAndRetry': 'التقط الصورة من جديد وحاول مرة ثانية.',
  'foodPhoto.removeImage': 'حذف الصورة {{number}}',
  'foodPhoto.addAnotherImage': 'إضافة صورة ثانية',
  'foodPhoto.add': 'إضافة',
  'foodPhoto.hiddenDetailsSingle':
    'أضف أي تفاصيل ما تبان بوضوح في الصورة.',
  'foodPhoto.hiddenDetailsMultiple':
    'أضف أي تفاصيل ما تبان بوضوح في الصور.',
  'foodPhoto.totalWeight': 'الوزن الإجمالي (اختياري)',
  'foodPhoto.weightPlaceholder': 'مثال: ٣٥٠',
  'foodPhoto.grams': 'غرام',
  'foodPhoto.ounces': 'أونصة',
  'foodPhoto.description': 'الوصف (اختياري)',
  'foodPhoto.descriptionHint':
    'اذكر الزيت والزبدة والكريمة والصوص والإضافات والأطباق الجانبية واسم المطعم.',
  'foodPhoto.descriptionPlaceholder': 'مثال: كبسة دجاج مع دقوس ولبن',
  'foodPhoto.generateEstimate': 'إنشاء التقدير',
  'foodPhoto.dismiss': 'إغلاق نافذة إضافة الصور',
  'foodPhoto.takePhoto': 'التقاط صورة',
  'foodPhoto.chooseLibrary': 'اختيار من مكتبة الصور',
  'foodPhoto.errorAiNotConfigured': 'الذكاء الاصطناعي غير مهيأ',
  'foodPhoto.errorAiNotConfiguredDescription':
    'أضف مزود ذكاء اصطناعي من نسخة الويب عشان تستخدم تقدير الصور.',
  'foodPhoto.errorImageTooLarge': 'حجم الصورة كبير',
  'foodPhoto.errorImageTooLargeDescription':
    'التقط صورة جديدة بجودة أقل.',
  'foodPhoto.errorUnexpectedFormat': 'صيغة الصورة غير مدعومة',
  'foodPhoto.errorUnexpectedFormatDescription': 'التقط صورة جديدة.',
  'foodPhoto.errorProcessFailed': 'ما قدرنا نعالج الصورة',
  'foodPhoto.errorProcessFailedDescription':
    'مزود الخدمة رفض الصورة. جرّب لقطة ثانية.',
  'foodPhoto.errorTimedOut': 'مزود الذكاء الاصطناعي تأخر بالرد',
  'foodPhoto.errorTimedOutDescription':
    'التقدير أخذ وقتًا أطول من المتوقع. حاول مرة ثانية، أو سجّل الصنف يدويًا.',
  'foodPhoto.errorProviderUnavailable':
    'ما قدرنا نوصل لمزود الذكاء الاصطناعي',
  'foodPhoto.errorProviderUnavailableDescription':
    'حاول مرة ثانية، أو سجّل الصنف يدويًا.',
  'foodPhoto.photoEstimateFallback': 'تقدير من صورة',
  'foodPhoto.nameRequired': 'اسم الصنف مطلوب',
  'foodPhoto.giveFoodName': 'اكتب اسمًا للصنف الغذائي.',
  'foodPhoto.invalidNutrition': 'القيم الغذائية غير صحيحة',
  'foodPhoto.requiredNutritionNonNegative':
    'لازم تكون السعرات والبروتين والكربوهيدرات والدهون أرقامًا موجبة أو صفرًا.',
  'foodPhoto.allNutritionNonNegative':
    'لازم تكون كل القيم الغذائية أرقامًا موجبة أو صفرًا.',
  'foodPhoto.invalidServingSize': 'حجم الحصة غير صحيح',
  'foodPhoto.servingSizePositive': 'لازم يكون حجم الحصة رقمًا أكبر من صفر.',
  'foodPhoto.reviewEstimate': 'مراجعة التقدير',
  'foodPhoto.estimateConfidence': 'تقدير {{confidence}}',
  'foodPhoto.totalEstimatedWeight': 'الوزن الإجمالي التقديري: {{weight}}',
  'foodPhoto.showDetectedIngredients': 'عرض المكوّنات المكتشفة',
  'foodPhoto.hideDetectedIngredients': 'إخفاء المكوّنات المكتشفة',
  'foodPhoto.overallConfidence.high': 'جيد',
  'foodPhoto.overallConfidence.medium': 'متوسط',
  'foodPhoto.overallConfidence.low': 'تقريبي',
  'foodPhoto.itemConfidence.high': 'مرجّح',
  'foodPhoto.itemConfidence.medium': 'محتمل',
  'foodPhoto.itemConfidence.low': 'غير مؤكّد',
  'foodPhoto.logEntry': 'تسجيل الصنف',
  'foodPhoto.estimateSaved': 'تم حفظ التقدير',
  'foodPhoto.selectMealType': 'اختر نوع الوجبة',
  'foodPhoto.invalidServings': 'عدد الحصص غير صحيح',
  'foodPhoto.servingsPositive': 'لازم يكون عدد الحصص رقمًا أكبر من صفر.',

  'foodScan.barcode': 'الباركود',
  'foodScan.label': 'الملصق',
  'foodScan.photo': 'الصورة',
  'foodScan.cameraPermission': 'نحتاج إذنك عشان نشغّل الكاميرا',
  'foodScan.grantPermission': 'السماح بالكاميرا',
  'foodScan.capturePhotoFailed': 'ما قدرنا نلتقط الصورة.',
  'foodScan.analyzeLabelFailed':
    'ما قدرنا نحلل الملصق الغذائي. حاول مرة ثانية.',
  'foodScan.analyzingLabel': 'جاري تحليل الملصق…',
  'foodScan.retake': 'إعادة التصوير',
  'foodScan.usePhoto': 'استخدام الصورة',
  'foodScan.lookupFailed': 'ما قدرنا نبحث عن الباركود',
  'foodScan.lookupFailedDescription':
    'ما قدرنا نبحث عن هالباركود. حاول مرة ثانية.',
  'foodScan.noBarcodeMatch': 'ما لقينا منتج بهالباركود',
  'foodScan.noBarcodeMatchDescription':
    'تقدر تمسح الملصق الغذائي أو تضيف الصنف يدويًا.',
  'foodScan.scanNutritionLabel': 'مسح الملصق الغذائي',
  'foodScan.addFoodManually': 'إضافة صنف يدويًا',
  'foodScan.frameWholeMeal': 'خل الوجبة كاملة داخل الإطار',
  'foodScan.aiNotConfigured':
    'تقدير الصور بالذكاء الاصطناعي غير مهيأ',
  'foodScan.aiNotConfiguredDescription':
    'افتح سباركي فتنس من المتصفح، ومن الإعدادات ثم الذكاء الاصطناعي أضف مزودًا للخدمة، وبعدها ارجع هنا.',
  'foodScan.logManually': 'تسجيل يدوي',
  'foodScan.notNow': 'مو الحين',
  'foodScan.typeBarcodeInstead': 'كتابة الباركود بدل المسح',
  'foodScan.choosePhotoLibrary': 'اختيار صورة من المكتبة',
  'foodScan.photoHelp': 'شرح تقدير الوجبة من صورة',
  'foodScan.enterBarcode': 'أدخل الباركود',
  'foodScan.barcodePlaceholder': 'رقم الباركود',
  'foodScan.useBarcode': 'استخدام الباركود',
  'foodScan.lookup': 'بحث',
  'foodScan.invalidBarcode': 'الباركود غير صحيح',
  'foodScan.invalidBarcodeDescription':
    'الباركود لازم يكون من ٨ إلى ١٤ رقمًا.',
  'foodScan.noPhotoReturned': 'ما رجعت لنا صورة من مكتبة الصور.',
  'foodScan.flashlightOn': 'إطفاء الفلاش',
  'foodScan.flashlightOff': 'تشغيل الفلاش',
  'foodScan.captureLabel': 'التقاط صورة الملصق الغذائي',
  'foodScan.captureMeal': 'التقاط صورة الوجبة',

  'onboarding.appName': 'سباركي فتنس',
  'onboarding.tagline': 'تابع صحتك ولياقتك على خادمك الخاص',
  'onboarding.serverUrl': 'رابط سباركي فتنس',
  'onboarding.serverUrlPlaceholder': 'https://sparky.example.com',
  'onboarding.pasteUrl': 'لصق الرابط من الحافظة',
  'onboarding.enterValidUrl': 'أدخل رابطًا صحيحًا لسباركي فتنس.',
  'onboarding.serverUnreachable':
    'ما قدرنا نوصل للخادم. تأكد من الرابط وحاول مرة ثانية.',
  'onboarding.learnMore': 'وش يقدم سباركي فتنس؟',
  'onboarding.learnMoreTracking':
    'يجمع لك سباركي فتنس تسجيل الأكل والتمارين والبيانات الصحية في مكان واحد.',
  'onboarding.learnMorePrivacy':
    'ويشتغل على خادمك الخاص عشان تبقى بياناتك تحت تحكمك.',
  'onboarding.signIn': 'تسجيل الدخول',
  'onboarding.sso': 'دخول موحّد',
  'onboarding.passkey': 'مفتاح مرور',
  'onboarding.apiKey': 'مفتاح API',
  'onboarding.connectTitle': 'الاتصال بسباركي فتنس',
  'onboarding.email': 'البريد الإلكتروني',
  'onboarding.password': 'كلمة المرور',
  'onboarding.orSignInWith': 'أو سجّل عن طريق',
  'onboarding.signInWithProvider': 'الدخول عن طريق {{provider}}',
  'onboarding.signInWithPasskey': 'الدخول بمفتاح المرور',
  'onboarding.noSignInMethods':
    'ما فيه طريقة دخول عادية مفعّلة على هالخادم. استخدم مفتاح API أو تواصل مع مسؤول الخادم.',
  'onboarding.pasteApiKey': 'لصق مفتاح API من الحافظة',
  'onboarding.connect': 'اتصال',
  'onboarding.mfaTitle': 'التحقق بخطوتين',
  'onboarding.emailRequired': 'اكتب بريدك الإلكتروني.',
  'onboarding.passwordRequired': 'اكتب كلمة المرور.',
  'onboarding.apiKeyRequired': 'اكتب مفتاح API.',
  'onboarding.invalidCredentials':
    'البريد الإلكتروني أو كلمة المرور غير صحيحة.',
  'onboarding.signInFailed':
    'ما قدرنا نتصل بالخادم. تأكد من الرابط وحاول مرة ثانية.',
  'onboarding.oidcFailed': 'ما قدرنا نسجّل دخولك عن طريق مزود الهوية.',
  'onboarding.passkeyFailed': 'ما قدرنا نسجّل دخولك بمفتاح المرور.',
  'onboarding.invalidApiKey': 'مفتاح API غير صحيح. تأكد منه وحاول مرة ثانية.',
  'onboarding.connectionFailedStatus': 'الخادم رفض الاتصال (الرمز {{status}}).',
  'onboarding.apiConnectionFailed':
    'ما قدرنا نتصل بالخادم باستخدام مفتاح API.',
  'onboarding.verificationCodeRequired': 'اكتب رمز التحقق.',
  'onboarding.tooManyAttempts':
    'المحاولات كثيرة. انتظر شوي وحاول مرة ثانية.',
  'onboarding.invalidVerificationCode':
    'رمز التحقق غير صحيح. حاول مرة ثانية.',
  'onboarding.sessionExpired':
    'انتهت جلسة الدخول. سجّل دخولك من جديد.',
  'onboarding.verificationFailed': 'ما قدرنا نتحقق من الرمز. حاول مرة ثانية.',
  'onboarding.sendEmailCodeFailed':
    'ما قدرنا نرسل رمز البريد. حاول مرة ثانية.',

  'mfa.authenticatorApp': 'تطبيق المصادقة',
  'mfa.emailCode': 'رمز البريد',
  'mfa.authenticatorInstructions': 'اكتب الرمز الظاهر في تطبيق المصادقة.',
  'mfa.emailSentInstructions': 'اكتب الرمز اللي أرسلناه لبريدك.',
  'mfa.emailSendInstructions':
    'اضغط الزر تحت عشان نرسل رمز التحقق لبريدك.',
  'mfa.sendCode': 'إرسال الرمز',
  'mfa.codePlaceholder': '٠٠٠٠٠٠',
  'mfa.verify': 'تحقق',
  'mfa.resendCode': 'إعادة إرسال الرمز',
  'mfa.useApiKey': 'استخدام مفتاح API بدلًا منه',

  'server.httpsRequired':
    'لازم تستخدم HTTPS عشان نحمي مفاتيح المرور والكاميرا ومزامنة البيانات الصحية وفق متطلبات {{healthPolicy}}.',

  'mealTypeDetail.noServerTitle': 'ما فيه خادم مربوط',
  'mealTypeDetail.noServerDescription':
    'اربط خادمك من الإعدادات عشان تشوف تغذية وجبتك.',
  'mealTypeDetail.loading': 'جاري تحميل الوجبة…',
  'mealTypeDetail.loadFailed': 'ما قدرنا نحمّل الوجبة',
  'mealTypeDetail.loadFailedDescription': 'تأكد من اتصالك وحاول مرة ثانية.',
  'mealTypeDetail.emptyTitle': 'ما فيه أصناف في {{meal}}',
  'mealTypeDetail.emptyDescription': 'ما سجلت أصناف في هالوجبة يوم {{date}}.',
  'mealTypeDetail.foods': 'الأصناف',
  'mealTypeDetail.copyMeal': 'نسخ الوجبة ليوم ثاني',
  'mealTypeDetail.food.one': 'صنف واحد',
  'mealTypeDetail.food.two': 'صنفين',
  'mealTypeDetail.food.few': '{{count}} أصناف',
  'mealTypeDetail.food.other': '{{count}} صنف',

  'copyMeal.title': 'نسخ {{meal}}',
  'copyMeal.from': 'من {{date}}',
  'copyMeal.targetDate': 'التاريخ الجديد',
  'copyMeal.targetMeal': 'الوجبة الجديدة',
  'copyMeal.copying': 'جاري النسخ…',
  'copyMeal.copy': 'نسخ الوجبة',
  'copyMeal.copied': 'تم نسخ الوجبة',
  'copyMeal.failed': 'ما قدرنا ننسخ الوجبة',

  'foodUnit.selectUnit': 'اختيار الوحدة',
  'foodUnit.savedCustomUnits': 'وحداتك المحفوظة',
  'foodUnit.group.weight': 'الوزن',
  'foodUnit.group.volume': 'الحجم',
  'foodUnit.group.quantity': 'العدد',
  'foodUnit.updateFailed': 'ما قدرنا نحدّث هالوحدة',
  'foodUnit.aiEstimate': 'تقدير بالذكاء الاصطناعي',
  'foodUnit.aiEstimateConfidence':
    'تقدير بالذكاء الاصطناعي (ثقة {{confidence}})',
  'foodUnit.confidence.high': 'عالية',
  'foodUnit.confidence.medium': 'متوسطة',
  'foodUnit.confidence.low': 'منخفضة',

  'foodForm.addFood': 'إضافة الصنف',
  'foodForm.foodName': 'اسم الصنف',
  'foodForm.foodNamePlaceholder': 'مثال: صدر دجاج',
  'foodForm.brand': 'العلامة التجارية',
  'foodForm.optional': 'اختياري',
  'foodForm.servingSize': 'حجم الحصة',
  'foodForm.servingUnit': 'وحدة الحصة',
  'foodForm.unitPlaceholder': 'وحدة',
  'foodForm.autoScaleNutrition': 'ضبط التغذية تلقائيًا',
  'foodForm.equivalentSizes': 'الأحجام المكافئة',
  'foodForm.removeEquivalent': 'حذف الحجم المكافئ',
  'foodForm.addEquivalent': '+ إضافة حجم مكافئ',
  'foodForm.manualUpdateTitle': 'تحديث القيم يدويًا',
  'foodForm.manualUpdateDescription':
    'ما نقدر نحوّل بين هالوحدات. حدّث القيم الغذائية يدويًا قبل الحفظ.',
  'foodForm.manualUpdateBanner':
    'ما نقدر نحوّل بين هالوحدات. حدّث القيم الغذائية يدويًا.',
  'foodForm.saveAnyway': 'حفظ على أي حال',
  'foodForm.couldNotEstimate': 'ما قدرنا نقدّر التحويل',
  'foodForm.noTrustedDefault': 'ما فيه حصة أساسية موثوقة نقدر نبني عليها.',
  'foodForm.setServingFirst': 'حدد حجم الحصة أول',
  'foodForm.untitledFood': 'صنف بدون اسم',
  'foodForm.estimateFailed': 'تعذر تقدير التحويل. حاول مرة ثانية.',
  'foodForm.estimating': 'جاري التقدير…',
  'foodForm.convertWithAi': 'تقدير التحويل بالذكاء الاصطناعي',
  'foodForm.aiEstimateConfidence': 'تقدير {{confidence}}',
  'foodForm.confidence.high': 'عالي الثقة',
  'foodForm.confidence.medium': 'متوسط الثقة',
  'foodForm.confidence.low': 'تقريبي',
  'foodForm.caloriesKcal': 'السعرات (كيلوسعرة)',

  'foodFormScreen.discardEquivalentsTitle': 'تبي تتجاهل الأحجام غير المحفوظة؟',
  'foodFormScreen.discardEquivalentsDescription':
    'عندك أحجام مكافئة ما حفظتها. تجاهلها عشان تكمل؟',
  'foodFormScreen.discard': 'تجاهل',
  'foodFormScreen.saveNutrition': 'حفظ القيم الغذائية',
  'foodFormScreen.variantExists':
    'الحصة «{{unit}}» محفوظة من قبل. تبي تحدّثها بهالقيم، أو تحفظها كحصة جديدة؟',
  'foodFormScreen.saveAsNew': 'حفظ كحصة جديدة',
  'foodFormScreen.updateExisting': 'تحديث الحالية',
  'foodFormScreen.missingName': 'اسم الصنف ناقص',
  'foodFormScreen.enterFoodName': 'اكتب اسم الصنف الغذائي.',
  'foodFormScreen.invalidServingSize': 'حجم الحصة غير صحيح',
  'foodFormScreen.servingSizePositive': 'لازم يكون حجم الحصة أكبر من صفر.',
  'foodFormScreen.barcode': 'الباركود',
  'foodFormScreen.invalidBarcode': 'الباركود غير صحيح',
  'foodFormScreen.barcodeDigits': 'الباركود لازم يكون من ٨ إلى ١٤ رقمًا.',
  'foodFormScreen.barcodeHelp':
    'اختياري. الباركود المعتاد يكون من ٨ إلى ١٤ رقمًا.',
  'foodFormScreen.scanCamera': 'مسح بالكاميرا',
  'foodFormScreen.foodSaved': 'تم حفظ الصنف',
  'foodFormScreen.noMealType': 'ما فيه نوع وجبة',
  'foodFormScreen.noMealTypeDescription':
    'ما عندك أنواع وجبات متاحة. راجع إعدادات حسابك.',
  'foodFormScreen.newFood': 'صنف غذائي جديد',
  'foodFormScreen.saveToLibrary': 'حفظ الصنف في المكتبة',
  'foodFormScreen.adjustNutrition': 'تعديل القيم الغذائية',
  'foodFormScreen.saveNutritionFuture': 'حفظ هالقيم للاستخدام لاحقًا',
  'foodFormScreen.editFood': 'تعديل الصنف',
  'foodFormScreen.loadingFoodDetails':
    'تفاصيل الصنف ما اكتملت؛ انتظر شوي وحاول مرة ثانية.',
  'foodFormScreen.saveNewUnitFailed': 'ما قدرنا نحفظ الوحدة الجديدة',
  'foodFormScreen.saveNewVariantFailed': 'ما قدرنا نحفظ الحصة الجديدة',
  'foodFormScreen.saveFutureFailed': 'ما قدرنا نحفظ القيم للاستخدام لاحقًا',
  'foodFormScreen.savedAsNewVariant': 'تم الحفظ كحصة جديدة',
  'foodFormScreen.saved': 'تم الحفظ',
  'foodFormScreen.savedWithEquivalents':
    'تم الحفظ وتحديث {{count}} من الأحجام المكافئة',
  'foodFormScreen.updateFoodFailed': 'ما قدرنا نحدّث الصنف',

  'editBarcode.forFood': 'للصنف: {{foodName}}',
  'editBarcode.anotherFood': 'صنف ثاني',
  'editBarcode.inUseTitle': 'الباركود مستخدم',
  'editBarcode.inUseDescription':
    'هالباركود مرتبط من قبل بـ «{{otherName}}». تبي تربطه بـ «{{foodName}}» على أي حال؟',
  'editBarcode.attach': 'ربط',
  'editBarcode.saved': 'تم حفظ الباركود',
  'editBarcode.saveFailed': 'ما قدرنا نحفظ الباركود',
  'editBarcode.tryAgain': 'جرّب مرة ثانية.',
  'editBarcode.removeTitle': 'حذف الباركود',
  'editBarcode.removeDescription': 'تبي تحذف الباركود من «{{foodName}}»؟',
  'editBarcode.remove': 'حذف',
  'editBarcode.removed': 'تم حذف الباركود',
  'editBarcode.removeFailed': 'ما قدرنا نحذف الباركود',
  'editBarcode.saveAccessibility': 'حفظ الباركود',

  'serverSettings.activeServer': 'الخادم النشط',
  'serverSettings.otherServers': 'خوادم ثانية',
  'serverSettings.empty': 'ما أضفت أي خادم للحين.',
  'serverSettings.openWeb': 'فتح لوحة الويب',
  'serverSettings.testConnection': 'اختبار الاتصال',
  'serverSettings.connected': 'الاتصال شغّال',
  'serverSettings.connectionFailed': 'فشل الاتصال',
  'serverSettings.optionsFor': 'خيارات الخادم {{url}}',
  'serverSettings.addServer': 'إضافة خادم',
  'serverSettings.addAccessibility': 'إضافة إعداد خادم جديد',
  'serverSettings.selectAction': 'وش تبي تسوي؟',
  'serverSettings.activeConfiguration': 'هذا هو الخادم النشط',
  'serverSettings.setActive': 'جعله الخادم النشط',
  'serverSettings.configure': 'تعديل الإعدادات',
  'serverSettings.delete': 'حذف',
  'serverSettings.deleteTitle': 'حذف الخادم؟',
  'serverSettings.deleteDescription':
    'متأكد تبي تحذف إعدادات {{url}} من التطبيق؟',
  'serverSettings.deleted': 'تم حذف الخادم',
  'serverSettings.noServersLeft':
    'ما بقى أي خادم محفوظ. أضف خادم عشان ترجع تستخدم التطبيق.',
  'serverSettings.deleteFailed': 'ما قدرنا نحذف الخادم',
  'serverSettings.activeChanged': 'تم تغيير الخادم النشط',
  'serverSettings.activeChangeFailed': 'ما قدرنا نغيّر الخادم النشط',
  'serverSettings.secureConnectionRequired': 'الاتصال الآمن مطلوب',
  'serverSettings.httpsRequired':
    'عدّل رابط الخادم وخله يبدأ بـ HTTPS عشان نحمي بياناتك.',
  'serverSettings.noServerTitle': 'ما فيه خادم مضاف',
  'serverSettings.noServerDescription': 'أضف خادم أول، وبعدها افتح لوحة الويب.',
  'serverSettings.openWebFailed': 'ما قدرنا نفتح لوحة الويب',
  'serverSettings.tryAgain': 'جرّب مرة ثانية.',

  'serverConfig.editServer': 'تعديل الخادم',
  'serverConfig.hidePassword': 'إخفاء كلمة المرور',
  'serverConfig.showPassword': 'إظهار كلمة المرور',
  'serverConfig.hideApiKey': 'إخفاء مفتاح API',
  'serverConfig.showApiKey': 'إظهار مفتاح API',
  'serverConfig.advancedOptions': 'خيارات متقدمة',
  'serverConfig.proxyHeaders': 'ترويسات الوكيل',
  'serverConfig.proxyHeadersHelp':
    'تحتاجها بعض إعدادات الوكيل العكسي قبل الوصول للخادم.',
  'serverConfig.addHeader': 'إضافة ترويسة',
  'serverConfig.removeHeader': 'حذف الترويسة رقم {{number}}',
  'serverConfig.headerNamePlaceholder': 'الاسم، مثل X-Access-Token',
  'serverConfig.headerValuePlaceholder': 'القيمة',
  'serverConfig.hideHeaderValue': 'إخفاء قيمة الترويسة',
  'serverConfig.showHeaderValue': 'إظهار قيمة الترويسة',
  'serverConfig.reservedHeaderTitle': 'ترويسة محجوزة',
  'serverConfig.reservedHeaderDescription':
    'قد تتعارض «{{name}}» مع ترويسة يضيفها التطبيق. تبي تكمل؟',
  'serverConfig.saveFailed': 'ما قدرنا نحفظ إعدادات الخادم. حاول مرة ثانية.',

  'reauth.sessionExpired': 'انتهت جلسة الدخول',
  'reauth.noServer': 'ما فيه خادم محدد. ارجع للإعدادات واختر خادم.',
  'reauth.server': 'الخادم',

  'passkeys.loadFailed': 'ما قدرنا نحمّل مفاتيح المرور',
  'passkeys.tryAgain': 'تأكد من اتصالك وحاول مرة ثانية.',
  'passkeys.registered': 'تمت إضافة مفتاح المرور',
  'passkeys.registeredDescription': 'صار جاهز للدخول الآمن والسريع.',
  'passkeys.cancelled': 'تم الإلغاء',
  'passkeys.cancelledDescription': 'ما تمت إضافة مفتاح المرور.',
  'passkeys.registrationFailed': 'ما قدرنا نضيف مفتاح المرور',
  'passkeys.nameRequiredTitle': 'سمِّ مفتاح المرور',
  'passkeys.nameRequiredDescription': 'اكتب اسمًا يسهّل عليك تمييزه لاحقًا.',
  'passkeys.deleteTitle': 'حذف مفتاح المرور؟',
  'passkeys.deleteDescription': 'متأكد تبي تحذف «{{name}}»؟',
  'passkeys.deleted': 'تم حذف مفتاح المرور',
  'passkeys.deletedDescription': 'ما عاد يقدر يسجّل دخولك.',
  'passkeys.deleteFailed': 'ما قدرنا نحذف مفتاح المرور',
  'passkeys.sessionOnly':
    'مفاتيح المرور متاحة للخوادم اللي تستخدم تسجيل الدخول بالحساب.',
  'passkeys.apiKeyUnsupported':
    'إذا كنت متصلًا بمفتاح API، غيّر طريقة الدخول أول.',
  'passkeys.server': 'الخادم:',
  'passkeys.description':
    'سجّل دخولك بأمان عن طريق بصمة الوجه أو الإصبع أو رمز قفل جهازك، بدون كلمة مرور.',
  'passkeys.emptyTitle': 'ما عندك مفاتيح مرور',
  'passkeys.emptyDescription':
    'أضف هالجهاز عشان يكون دخولك أسرع المرة الجاية.',
  'passkeys.unnamed': 'مفتاح مرور بدون اسم',
  'passkeys.registeredAt': 'أُضيف في {{date}}',
  'passkeys.deleteAccessibility': 'حذف {{name}}',
  'passkeys.add': 'إضافة مفتاح مرور',
  'passkeys.registerTitle': 'إضافة مفتاح مرور',
  'passkeys.registerDescription':
    'اختر له اسمًا واضحًا عشان تعرفه لاحقًا، مثل «جوالي».',
  'passkeys.namePlaceholder': 'مثل: جوالي',

  'healthMetric.steps': 'الخطوات',
  'healthMetric.calories': 'السعرات النشطة',
  'healthMetric.totalCalories': 'إجمالي السعرات المحروقة',
  'healthMetric.heartRate': 'معدل نبض القلب',
  'healthMetric.weight': 'الوزن',
  'healthMetric.bloodPressure': 'ضغط الدم',
  'healthMetric.nutrition': 'التغذية',
  'healthMetric.sleepSession': 'النوم',
  'healthMetric.stress': 'التوتر',
  'healthMetric.basalBodyTemperature': 'درجة حرارة الجسم الأساسية',
  'healthMetric.basalMetabolicRate': 'معدل الأيض الأساسي',
  'healthMetric.bloodGlucose': 'سكر الدم',
  'healthMetric.bodyFat': 'نسبة دهون الجسم',
  'healthMetric.bodyTemperature': 'درجة حرارة الجسم',
  'healthMetric.distance': 'المسافة',
  'healthMetric.exerciseSession': 'جلسات التمرين',
  'healthMetric.floorsClimbed': 'الطوابق التي صعدتها',
  'healthMetric.height': 'الطول',
  'healthMetric.hydration': 'شرب الماء',
  'healthMetric.leanBodyMass': 'كتلة الجسم الخالية من الدهون',
  'healthMetric.respiratoryRate': 'معدل التنفس',
  'healthMetric.restingHeartRate': 'نبض القلب وقت الراحة',
  'healthMetric.heartRateVariability': 'تباين معدل نبض القلب',
  'healthMetric.vo2Max': 'الحد الأقصى لاستهلاك الأكسجين (VO₂ max)',
  'healthMetric.wheelchairPushes': 'دفعات الكرسي المتحرك',
  'healthMetric.speed': 'السرعة',
  'healthMetric.power': 'القدرة',
  'healthMetric.elevationGained': 'الارتفاع المكتسب',
  'healthMetric.boneMass': 'كتلة العظام',
  'healthMetric.cervicalMucus': 'مخاط عنق الرحم',
  'healthMetric.cyclingPedalingCadence': 'معدل دواسات الدراجة',
  'healthMetric.intermenstrualBleeding': 'النزيف بين الدورات',
  'healthMetric.menstruationPeriod': 'فترة الدورة الشهرية',
  'healthMetric.ovulationTest': 'اختبار الإباضة',
  'healthMetric.stepsCadence': 'معدل الخطوات',
  'healthMetric.bloodOxygenSaturation': 'تشبع الأكسجين في الدم',
  'healthMetric.bloodAlcoholContent': 'نسبة الكحول في الدم',
  'healthMetric.menstruationFlow': 'تدفق الدورة الشهرية',
  'healthMetric.nutritionDietaryFatTotal': 'إجمالي الدهون الغذائية',
  'healthMetric.nutritionDietaryProtein': 'البروتين الغذائي',
  'healthMetric.nutritionDietarySodium': 'الصوديوم الغذائي',
  'healthMetric.walkingSpeed': 'سرعة المشي',
  'healthMetric.walkingStepLength': 'طول خطوة المشي',
  'healthMetric.walkingAsymmetryPercentage': 'نسبة عدم تماثل المشي',
  'healthMetric.walkingDoubleSupportPercentage': 'نسبة الارتكاز المزدوج أثناء المشي',
  'healthMetric.runningGroundContactTime': 'زمن ملامسة الأرض أثناء الجري',
  'healthMetric.runningStrideLength': 'طول خطوة الجري',
  'healthMetric.runningPower': 'قدرة الجري',
  'healthMetric.runningVerticalOscillation': 'التذبذب الرأسي أثناء الجري',
  'healthMetric.runningSpeed': 'سرعة الجري',
  'healthMetric.cyclingSpeed': 'سرعة الدراجة',
  'healthMetric.cyclingPower': 'قدرة الدراجة',
  'healthMetric.cyclingCadence': 'معدل دواسات الدراجة',
  'healthMetric.cyclingFunctionalThresholdPower': 'القدرة الوظيفية القصوى للدراجة',
  'healthMetric.environmentalAudioExposure': 'التعرض للأصوات المحيطة',
  'healthMetric.headphoneAudioExposure': 'التعرض لصوت سماعات الرأس',
  'healthMetric.appleMoveTime': 'وقت الحركة من Apple',
  'healthMetric.appleExerciseTime': 'وقت التمرين من Apple',
  'healthMetric.appleStandTime': 'وقت الوقوف من Apple',

  'sync.range.today': 'اليوم',
  'sync.range.24h': 'آخر ٢٤ ساعة',
  'sync.range.3d': 'آخر ٣ أيام',
  'sync.range.7d': 'آخر ٧ أيام',
  'sync.range.30d': 'آخر ٣٠ يومًا',
  'sync.range.90d': 'آخر ٩٠ يومًا',
  'sync.range.180d': 'آخر ٦ شهور',
  'sync.range.365d': 'آخر سنة',
  'sync.rangeTitle': 'نطاق المزامنة',
  'sync.selectRange': 'اختيار نطاق المزامنة',
  'sync.rangeDescription': 'يحدد كمية البيانات اللي بتنرسل في المزامنة الجاية.',
  'sync.largeRangeWarning': 'النطاقات الطويلة ممكن تأخذ وقت.',
  'sync.now': 'زامن الحين',
  'sync.nowDescription': 'إرسال بياناتك الصحية إلى خادمك',
  'sync.syncing': 'جاري مزامنة البيانات الصحية…',
  'sync.complete': 'اكتملت المزامنة',
  'sync.completeDescription': 'تم تحديث بياناتك الصحية على الخادم.',
  'sync.incomplete': 'اكتملت المزامنة جزئيًا',
  'sync.readErrors': 'تعذر قراءة {{count}} من المؤشرات، وبنحاول مرة ثانية بالمزامنة الجاية.',
  'sync.uploadErrors': 'رفض الخادم {{count}} من السجلات. التفاصيل موجودة في السجل التقني.',
  'sync.failed': 'ما تمت المزامنة',
  'sync.failedDescription': 'تأكد من الاتصال والصلاحيات وحاول مرة ثانية.',
  'sync.backgroundTitle': 'المزامنة بالخلفية',
  'sync.backgroundToggle': 'تشغيل المزامنة بالخلفية',
  'sync.backgroundDescriptionIos':
    'يحدّث التطبيق بياناتك بالخلفية متى ما سمح الجهاز. وتقدر تزامن يدويًا بأي وقت.',
  'sync.onOpenTitle': 'المزامنة عند فتح التطبيق',
  'sync.onOpenToggle': 'المزامنة تلقائيًا عند الفتح',
  'sync.onOpenDescription':
    'يحدّث بياناتك الصحية تلقائيًا كل ما فتحت التطبيق.',
  'sync.source': 'المصدر:',
  'sync.healthConnectSettings': 'إعدادات Health Connect',
  'sync.appleHealthSettings': 'إعدادات تطبيق صحتي',
  'sync.appleHealthName': 'صحتي من Apple',
  'sync.permissionRequired': 'الصلاحية مطلوبة',
  'sync.permissionsRequired': 'بعض الصلاحيات ناقصة',
  'sync.permissionDenied': 'الصلاحية غير مفعّلة',
  'sync.permissionError': 'ما قدرنا نطلب الصلاحية',
  'sync.permissionErrorDescription':
    'افتح إعدادات الصحة وفعّل الصلاحية، ثم حاول مرة ثانية.',
  'sync.backgroundPermissionDescription':
    'المزامنة بالخلفية تحتاج صلاحية الوصول بالخلفية من إعدادات Health Connect.',
  'sync.readPermissionDescription':
    'فعّل صلاحية قراءة «{{metric}}» من {{settings}}.',
  'sync.writePermissionDescription':
    'فعّل صلاحية كتابة «{{metric}}» من {{settings}}.',
  'sync.metricPermissionErrorDescription':
    'ما قدرنا نطلب صلاحية «{{metric}}». افتح إعدادات الصحة وفعّلها يدويًا.',
  'sync.allPermissionsDescription':
    'فعّل كل صلاحيات الصحة المطلوبة من {{settings}} عشان تزامن جميع البيانات.',
  'sync.removed': 'تم حذف البيانات',
  'sync.removedDescription': 'حذفنا بيانات سباركي فتنس من {{store}}.',
  'sync.partiallyRemoved': 'انحذف جزء من البيانات',
  'sync.partiallyRemovedDescription':
    'بعض السجلات ما قدرنا نحذفها من {{store}}.',
  'sync.removeFailed': 'ما قدرنا نحذف البيانات',
  'sync.removeFailedDescription': 'حاول مرة ثانية من {{store}}.',
  'sync.removeAllTitle': 'حذف كل بيانات سباركي فتنس من {{store}}؟',
  'sync.removeAllDescription':
    'بنحذف سجلات التغذية وشرب الماء اللي كتبها سباركي فتنس في {{store}}، وبنوقف الكتابة. يومياتك في سباركي فتنس وبيانات التطبيقات الثانية ما تتأثر.',
  'sync.healthConnectUnavailable':
    'Health Connect غير متاح. تأكد إنه مثبت ومفعّل على جهازك.',
  'sync.appleHealthUnavailable':
    'بيانات الصحة غير متاحة. فعّل صلاحية «صحتي» من إعدادات جهازك.',
  'sync.lastSynced': 'آخر مزامنة:',
  'sync.medicalDisclaimerTitle': 'هذه المعلومات ليست نصيحة طبية.',
  'sync.medicalDisclaimerDescription':
    'استشر مختصًا صحيًا عند الحاجة إلى تشخيص أو علاج أو نصيحة طبية.',
  'sync.reportTitle': 'تقرير البيانات الصحية',
  'sync.generatingReport': 'جاري تجهيز التقرير…',
  'sync.reportDescription': 'تصدير بيانات مجهّلة للمساعدة في حل المشاكل',
  'sync.reportPrivacy':
    'يقرأ آخر ٤ ساعات من Health Connect للتشخيص، ويقرّب القيم لحماية خصوصيتك. ما ينرسل شيء تلقائيًا.',
  'sync.reportFailed': 'ما قدرنا نجهّز التقرير',
  'sync.reportFailedDescription': 'حاول مرة ثانية بعد ما تتأكد من صلاحيات الصحة.',

  'healthCategory.Common': 'الشائعة',
  'healthCategory.Vitals': 'المؤشرات الحيوية',
  'healthCategory.Body Measurements': 'قياسات الجسم',
  'healthCategory.Nutrition': 'التغذية',
  'healthCategory.Activity': 'النشاط',
  'healthCategory.Reproductive': 'الصحة الإنجابية',
  'healthCategory.Mobility': 'الحركة',
  'healthCategory.Running': 'الجري',
  'healthCategory.Cycling': 'ركوب الدراجة',
  'healthCategory.Environment': 'البيئة',
  'healthCategory.Apple': 'Apple',
  'healthCategory.Other': 'أخرى',
  'section.item.one': 'عنصر واحد',
  'section.item.two': 'عنصرين',
  'section.item.few': '{{count}} عناصر',
  'section.item.other': '{{count}} عنصر',
  'section.collapse': 'طي هذا القسم',
  'section.expand': 'توسيع هذا القسم',

  'healthSync.dataTitle': 'البيانات الصحية للمزامنة',
  'healthSync.appleSummary':
    'يقرأ البيانات التي تختارها من صحتي ويزامنها مع خادمك الخاص.',
  'healthSync.healthConnectSummary':
    'يقرأ البيانات التي تختارها من Health Connect ويزامنها مع خادمك الخاص.',
  'healthSync.appleDetail':
    'يقرأ سباركي فتنس البيانات الصحية التي تحددها عبر صحتي (HealthKit). عند تفعيل المزامنة، تُنقل البيانات بين جهازك وخادم سباركي فتنس المستضاف ذاتيًا فقط، سواء أثناء المزامنة اليدوية أو في الخلفية.\n\nيمكنك إدارة الصلاحية أو إلغاؤها من: الإعدادات ← الصحة ← الوصول إلى البيانات والأجهزة ← SparkyFitnessMobile.',
  'healthSync.healthConnectDetail':
    'يقرأ سباركي فتنس البيانات الصحية التي تحددها عبر Health Connect. عند تفعيل المزامنة، تُنقل البيانات بين جهازك وخادم سباركي فتنس المستضاف ذاتيًا فقط، سواء أثناء المزامنة اليدوية أو في الخلفية.',
  'healthSync.learnMore': 'اعرف أكثر',
  'healthSync.showLess': 'عرض أقل',
  'healthSync.enableAll': 'تفعيل كل المؤشرات الصحية',
  'healthSync.batteryWarning':
    'تفعيل مؤشرات كثيرة ممكن يزيد استهلاك البطارية؛ كل مؤشر مفعّل قد يوقظ التطبيق بالخلفية عند وصول بيانات جديدة.',
  'healthSync.metricAccessibility': 'مزامنة {{metric}}',
  'healthSync.noData': 'ما فيه بيانات',
  'healthSync.readError': 'تعذرت القراءة',
  'healthSync.record.one': 'سجل واحد',
  'healthSync.record.two': 'سجلين',
  'healthSync.record.few': '{{count}} سجلات',
  'healthSync.record.other': '{{count}} سجل',
  'healthSync.workoutRecord.one': 'تمرين واحد',
  'healthSync.workoutRecord.two': 'تمرينين',
  'healthSync.workoutRecord.few': '{{count}} تمارين',
  'healthSync.workoutRecord.other': '{{count}} تمرين',

  'healthWriteback.title': 'الكتابة إلى {{store}}',
  'healthWriteback.description':
    'يرسل بيانات التغذية وشرب الماء اللي تسجلها في سباركي فتنس إلى {{store}}.',
  'healthWriteback.removeTitle': 'حذف بيانات من {{store}}',
  'healthWriteback.allTime': 'كل الفترات',
  'healthWriteback.dateRange': 'اختيار نطاق زمني…',
  'healthWriteback.removeAction': 'حذف بيانات سباركي فتنس من {{store}}',
  'healthWriteback.metricAccessibility': 'الكتابة إلى {{metric}}',
  'healthWriteback.rangeTitle': 'اختر الفترة التي تريد حذف بياناتها',
  'healthWriteback.removeRange': 'حذف بيانات الفترة المحددة',

  'exerciseCategory.strength': 'قوة',
  'exerciseCategory.cardio': 'لياقة قلبية',
  'exerciseCategory.flexibility': 'مرونة',
  'exerciseCategory.balance': 'توازن',
  'exerciseCategory.mobility': 'حركة',
  'exerciseCategory.endurance': 'تحمّل',
  'exerciseCategory.sports': 'رياضة',
  'exerciseCategory.other': 'أخرى',

  'settings.server': 'الخادم',
  'settings.addServer': 'اضغط لإضافة خادم',
  'settings.lastSynced': 'آخر مزامنة {{time}}',
  'settings.serverAccessibilityConnected': 'إعدادات الخادم. الاتصال شغال.',
  'settings.serverAccessibilityFailed': 'إعدادات الخادم. تعذر الاتصال.',
  'settings.serverAccessibilityMissing': 'إعدادات الخادم. ما فيه خادم مربوط.',
  'settings.shareDiagnostic': 'مشاركة تقرير التشخيص',
  'settings.diagnosticDescription':
    'يصدّر تقريرًا محليًا عن إصدار التطبيق وحالة المزامنة والسجل التقني. ما يشمل بياناتك الصحية أو أصنافك الغذائية، ولا يرسل أي شيء تلقائيًا.',
  'settings.shareFailed': 'ما قدرنا نجهّز التقرير. حاول مرة ثانية.',

  'logs.level.error': 'أخطاء',
  'logs.level.warning': 'تحذيرات',
  'logs.level.info': 'معلومات',
  'logs.level.debug': 'تصحيح الأخطاء',
  'logs.all': 'الكل',
  'logs.clearTitle': 'مسح السجل التقني',
  'logs.clearDescription':
    'هل تريد مسح جميع السجلات التقنية؟ لا يمكن التراجع عن هذا الإجراء.',
  'logs.clearAction': 'مسح',
  'logs.clearAccessibility': 'مسح السجل التقني',
  'logs.filterSaveFailed': 'تعذر حفظ تصفية السجل التقني.',
  'logs.copyStatus': 'الحالة: {{status}}',
  'logs.copyMessage': 'الرسالة: {{message}}',
  'logs.copyDetails': 'التفاصيل: {{details}}',
  'logs.copyTimestamp': 'الوقت: {{timestamp}}',
  'logs.copied': 'تم النسخ',
  'logs.copiedDescription': 'تم نسخ السجل إلى الحافظة.',
  'logs.empty': 'ما فيه سجلات للحين.',
  'logs.noMatches': 'ما فيه سجلات تطابق التصفية الحالية.',
  'logs.count.one': 'عرض سجل واحد',
  'logs.count.two': 'عرض سجلين',
  'logs.count.few': 'عرض {{count}} سجلات',
  'logs.count.other': 'عرض {{count}} سجل',

  'chat.title': 'سباركي',
  'chat.errorTitle': 'تعذر الرد',
  'chat.errorDescription': 'ما ضبط الرد هالمرة. حاول مرة ثانية.',
  'chat.messageError': 'تعذر عرض الرد. حاول مرة ثانية.',
  'chat.retry': 'حاول مرة ثانية',
  'chat.copy': 'نسخ',
  'chat.copied': 'تم النسخ',
  'chat.composerPlaceholder': 'اكتب لسباركي…',
  'chat.send': 'إرسال الرسالة',
  'chat.stop': 'إيقاف الرد',
  'chat.emptyDescription': 'اسأل سباركي عن تغذيتك أو تمارينك أو أهدافك.',
  'chat.suggestion.breakfast': 'سجّل بيضتين وموزة على الفطور',
  'chat.suggestion.run': 'سجّل لي جري لمدة ٣٠ دقيقة اليوم',
  'chat.suggestion.calories': 'كم باقي لي من السعرات اليوم؟',
  'chat.suggestion.snack': 'اقترح لي وجبة خفيفة غنية بالبروتين',
  'chat.clearTitle': 'حذف محادثة سباركي',
  'chat.clearDescription':
    'سيُحذف سجل محادثتك مع سباركي نهائيًا. لا يمكن التراجع عن هذا الإجراء.',
  'chat.clearAccessibility': 'حذف محادثة سباركي',
  'chat.clearFailed': 'تعذر حذف المحادثة',
  'chat.noServer': 'لا يوجد خادم نشط. أضف خادمًا من الإعدادات أولًا.',
  'chat.noProvider':
    'لا يوجد مزود ذكاء اصطناعي نشط. قم بإعداده من تطبيق الويب أولًا.',
  'chat.typing': 'سباركي يكتب',
  'chat.tool.manageFood': 'تسجيل الطعام',
  'chat.tool.manageExercise': 'تسجيل التمارين',
  'chat.tool.manageCheckin': 'تسجيل القياسات',
  'chat.tool.manageGoals': 'إدارة الأهداف',
  'chat.tool.manageHabits': 'إدارة العادات',
  'chat.tool.manageProfile': 'إدارة الملف الشخصي',
  'chat.tool.trends30Days': 'الاطلاع على اتجاهات ٣٠ يومًا',
  'chat.tool.healthSummary': 'الاطلاع على الملخص الصحي',
  'chat.tool.databaseStats': 'الاطلاع على إحصاءات قاعدة البيانات',
  'chat.tool.userInfo': 'الاطلاع على معلومات المستخدم',
  'chat.tool.contextualNudge': 'الاطلاع على التوجيه المناسب',
  'chat.tool.loggingStreak': 'الاطلاع على سلسلة التسجيل',
  'chat.tool.dailyExerciseTotals': 'الاطلاع على إجمالي تمارين اليوم',
  'chat.tool.exerciseDetails': 'الاطلاع على تفاصيل التمرين',
  'chat.tool.exerciseDiary': 'الاطلاع على يوميات التمارين',
  'chat.tool.exerciseProgress': 'الاطلاع على تقدم التمارين',
  'chat.tool.exerciseUsage': 'الاطلاع على استخدام التمرين',
  'chat.tool.recentExerciseEntries': 'الاطلاع على أحدث تسجيلات التمارين',
  'chat.tool.foodDetails': 'الاطلاع على تفاصيل الصنف الغذائي',
  'chat.tool.foodDiary': 'الاطلاع على يوميات الطعام',
  'chat.tool.foodUsage': 'الاطلاع على استخدام الصنف الغذائي',
  'chat.tool.nutritionSummary': 'الاطلاع على ملخص التغذية',
  'chat.tool.recentFoodEntries': 'الاطلاع على أحدث تسجيلات الطعام',
  'chat.tool.goalSnapshot': 'الاطلاع على ملخص الأهداف',
  'chat.tool.dailyReport': 'الاطلاع على التقرير اليومي',
  'chat.tool.report': 'الاطلاع على التقرير',
  'chat.tool.searchFoods': 'البحث عن أصناف غذائية',
  'chat.tool.searchExercises': 'البحث عن تمارين',
  'chat.tool.lookup': 'جلب البيانات',
  'chat.tool.generic': 'أداة سباركي',
  'chat.tool.status.running': '{{tool}}، جارٍ التنفيذ',
  'chat.tool.status.complete': '{{tool}}، اكتمل',
  'chat.tool.status.error': '{{tool}}، تعذر التنفيذ',
  'chat.tool.expandHint': 'عرض التفاصيل',
  'chat.tool.collapseHint': 'إخفاء التفاصيل',

  'diary.chooseDate': 'اختيار تاريخ اليوميات',
  'diary.previousDay': 'اليوم السابق',
  'diary.nextDay': 'اليوم التالي',
  'diary.openCalendar': 'اختيار التاريخ',
  'diary.noServerTitle': 'ما فيه خادم مربوط',
  'diary.noServerDescription': 'اربط خادمك من الإعدادات عشان تشوف يومياتك.',
  'diary.loading': 'جاري تحميل يومياتك…',
  'diary.loadError': 'ما قدرنا نحمّل يومياتك',
  'diary.loadErrorDescription': 'تأكد من اتصالك وحاول مرة ثانية.',
  'diary.emptyDay': 'ما فيه تسجيلات لهاليوم',
  'diary.addFood': 'إضافة صنف غذائي',
  'diary.tapToAddFood': 'اضغط لإضافة صنف غذائي',
  'diary.nutritionBreakdown': 'تفاصيل تغذية {{meal}}',
  'diary.tapToAddExercise': 'اضغط لإضافة تمرين',
  'diary.addExercise': 'إضافة تمرين',
  'diary.exercise': 'التمارين',
  'diary.measurements': 'القياسات',
  'diary.editMeasurements': 'تعديل القياسات',
  'diary.unknownFood': 'صنف غير معروف',
  'diary.saving': 'جاري الحفظ…',
  'diary.viewDetails': 'عرض التفاصيل',
  'diary.adjustServing': 'تعديل الحصة',
  'diary.deleteFood': 'حذف التسجيل الغذائي',
  'diary.deleteExercise': 'حذف التمرين',

  'delete.failedTitle': 'ما قدرنا نحذف',
  'delete.foodEntryTitle': 'حذف التسجيل',
  'delete.foodEntryDescription': 'متأكد تبي تحذف هالتسجيل الغذائي؟',
  'delete.mealTitle': 'حذف الوجبة',
  'delete.mealDescription': 'متأكد تبي تحذف هالوجبة؟',
  'delete.workoutTitle': 'حذف التمرين؟',
  'delete.workoutDescription': 'بينحذف التمرين وكل تفاصيله نهائيًا.',
  'delete.activityTitle': 'حذف النشاط؟',
  'delete.activityDescription': 'بينحذف النشاط نهائيًا.',

  'workout.unknownExercise': 'تمرين غير معروف',
  'workout.exercise.one': 'تمرين واحد',
  'workout.exercise.two': 'تمرينين',
  'workout.exercise.few': '{{count}} تمارين',
  'workout.exercise.other': '{{count}} تمرين',
  'workout.set.one': 'مجموعة واحدة',
  'workout.set.two': 'مجموعتين',
  'workout.set.few': '{{count}} مجموعات',
  'workout.set.other': '{{count}} مجموعة',
  'workout.rep.one': 'تكرار واحد',
  'workout.rep.two': 'تكرارين',
  'workout.rep.few': '{{count}} تكرارات',
  'workout.rep.other': '{{count}} تكرار',
  'workout.minute.one': 'دقيقة واحدة',
  'workout.minute.two': 'دقيقتين',
  'workout.minute.few': '{{count}} دقائق',
  'workout.minute.other': '{{count}} دقيقة',
  'workout.hour.one': 'ساعة',
  'workout.hour.two': 'ساعتين',
  'workout.hour.few': '{{count}} ساعات',
  'workout.hour.other': '{{count}} ساعة',
  'workoutCard.expandExercise': 'توسيع {{name}}',
  'workoutCard.collapseExercise': 'طي {{name}}',
  'workoutCard.viewExerciseDetails': 'عرض تفاصيل {{name}}',
  'workoutCard.moreOptions': 'خيارات إضافية لـ {{name}}',
  'workoutCard.last': 'المرة الماضية',
  'workoutCard.best': 'الأفضل',
  'workoutCard.setHeader': 'المجموعة',
  'workoutCard.repsHeader': 'التكرارات',
  'workoutCard.changeMetric': 'تغيير عمود القياس',
  'workoutCard.addSet': 'إضافة مجموعة',
  'workoutCard.addSetTo': 'إضافة مجموعة إلى {{name}}',
  'workoutCard.rest': 'راحة',
  'workoutCard.metricRpe': 'RPE',
  'workoutCard.metricVolume': 'حجم',
  'workoutCard.metricEstimatedOneRm': '1RM',
  'workoutCard.metricEstimatedTenRm': '10RM',
  'workoutSet.changeType': 'تغيير نوع المجموعة {{set}}',
  'workoutSet.uncomplete': 'إلغاء إكمال المجموعة {{set}}',
  'workoutSet.log': 'تسجيل المجموعة {{set}}',
  'workoutSet.markComplete': 'تحديد المجموعة {{set}} كمكتملة',
  'workoutSet.weight': 'الوزن',
  'workoutSet.reps': 'التكرارات',
  'workoutSet.rpe': 'مقياس الجهد',
  'workoutSet.editWeight': 'تعديل وزن المجموعة {{set}}',
  'workoutSet.editReps': 'تعديل تكرارات المجموعة {{set}}',
  'workoutSet.editRpe': 'تعديل جهد المجموعة {{set}}',
  'workoutSet.delete': 'حذف المجموعة {{set}}',
  'workoutSet.next': 'التالي',
  'workoutSet.nextSet': 'المجموعة التالية',
  'workoutSet.warmupShort': 'إ',
  'workoutMenu.metricRpe': 'مقياس الجهد (RPE)',
  'workoutMenu.metricVolume': 'الحجم التدريبي',
  'workoutMenu.metricEstimatedOneRm': 'الوزن التقديري لتكرار واحد',
  'workoutMenu.metricEstimatedTenRm': 'الوزن التقديري لـ ١٠ تكرارات',
  'workoutMenu.setTypeWarmup': 'إحماء',
  'workoutMenu.setTypeNormal': 'عادية',
  'workoutMenu.setTypeDrop': 'تنازلية',
  'workoutMenu.setTypeFailure': 'حتى الفشل',
  'workoutMenu.deleteSet': 'حذف المجموعة',
  'restPeriod.title': 'مدة الراحة',
  'restPeriod.custom': 'مدة مخصصة',
  'restPeriod.customSeconds': 'مدة الراحة بالثواني',
  'restPeriod.decrease': 'تقليل مدة الراحة ١٥ ثانية',
  'restPeriod.increase': 'زيادة مدة الراحة ١٥ ثانية',
  'workoutPresetDetail.deleted': 'تم حذف قالب التمرين',
  'workoutPresetDetail.editPreset': 'تعديل قالب التمرين',
  'workoutPresetDetail.starting': 'جاري بدء التمرين…',
  'workoutPresetDetail.startWorkout': 'ابدأ التمرين',
  'workoutPresetDetail.logPastWorkout': 'تسجيل تمرين سابق',
  'workoutPresetDetail.deleting': 'جاري حذف القالب…',
  'workoutPresetDetail.deletePreset': 'حذف القالب',
  'workoutPresetMutation.createFailed': 'ما قدرنا ننشئ قالب التمرين',
  'workoutPresetMutation.updateFailed': 'ما قدرنا نحدّث القالب',
  'workoutPresetMutation.deleteFailed': 'ما قدرنا نحذف القالب',
  'workoutPresetMutation.editForbidden': 'ليست لديك صلاحية تعديل هذا القالب.',
  'workoutPresetMutation.deleteForbidden': 'ليست لديك صلاحية حذف هذا القالب.',
  'workoutPresetMutation.deleteTitle': 'حذف قالب التمرين؟',
  'workoutPresetMutation.deleteDescription':
    'سيُحذف هذا القالب نهائيًا من مكتبتك.',
  'source.sparky': 'سباركي',
  'workoutDetail.replaceTitle': 'استبدال التمرين الحالي؟',
  'workoutDetail.replaceDescription':
    'عندك تمرين جارٍ. بدء هذا التمرين بيمسحه من التطبيق، والمجموعات المحفوظة بتبقى في يومياتك.',
  'workoutDetail.clearAndStart': 'مسح وبدء',
  'workoutDetail.startHere': 'ابدأ التمرين من هنا',
  'workoutDetail.needsExercise': 'لا يمكن حفظ التمرين بدون تمارين',
  'workoutDetail.needsExerciseDescription':
    'أضف تمرينًا واحدًا على الأقل مع مجموعة، أو احذف هذا التمرين.',
  'workoutDetail.saveFailed': 'ما قدرنا نحفظ التمرين',
  'workoutDetail.details': 'التفاصيل',
  'workoutDetail.exercises': 'التمارين',
  'workoutDetail.sets': 'المجموعات',
  'workoutDetail.volume': 'الحجم التدريبي',
  'workoutDetail.editTitle': 'تعديل التمرين',
  'workoutDetail.reorderExercises': 'إعادة ترتيب التمارين',
  'workoutDetail.editWorkout': 'تعديل التمرين',
  'workoutDetail.name': 'الاسم',
  'workoutDetail.namePlaceholder': 'اسم التمرين',
  'workoutDetail.chooseDate': 'اختيار تاريخ التمرين',
  'workoutDetail.startWorkout': 'ابدأ التمرين',
  'workoutDetail.notes': 'الملاحظات',
  'workoutDetail.notesPlaceholder': 'أضف ملاحظات…',
  'workoutDetail.deleting': 'جاري حذف التمرين…',
  'workoutDetail.deleteWorkout': 'حذف التمرين',
  'activityDetail.averageHeartRate': 'متوسط النبض',
  'activityDetail.maxHeartRate': 'أعلى نبض',
  'activityDetail.elevationGain': 'الارتفاع المكتسب',
  'activityDetail.averageCadence': 'متوسط الإيقاع',
  'activityDetail.zone': 'المنطقة {{zone}}',
  'activityDetail.heartRateZone': 'منطقة النبض {{zone}}',

  'dashboard.chooseDate': 'اختيار تاريخ الرئيسية',
  'dashboard.range7d': '٧ أيام',
  'dashboard.range30d': '٣٠ يوم',
  'dashboard.range90d': '٩٠ يوم',
  'dashboard.noServerTitle': 'ما فيه خادم مربوط',
  'dashboard.noServerDescription':
    'اربط خادمك من الإعدادات عشان تشوف ملخص يومك.',
  'dashboard.loading': 'جاري تحميل ملخص يومك…',
  'dashboard.loadError': 'ما قدرنا نحمّل ملخص يومك',
  'dashboard.loadErrorDescription': 'تأكد من اتصالك وحاول مرة ثانية.',
  'dashboard.askSparky': 'اسأل سباركي…',
  'dashboard.macronutrients': 'العناصر الكبرى',
  'dashboard.food': 'الأكل',
  'dashboard.tapToAddFood': 'اضغط لإضافة صنف غذائي',
  'dashboard.healthTrends': 'مؤشراتك الصحية',
  'dashboard.consumed': 'المستهلك',
  'dashboard.burned': 'المحروق',
  'dashboard.remaining': 'المتبقي',
  'dashboard.calorieGoal': 'من هدف {{goal}} سعرة',
  'dashboard.exercise': 'التمارين',
  'dashboard.minutes': 'الدقائق',
  'dashboard.calories': 'السعرات',
  'dashboard.noExercise': 'ما سجّلت تمرين للحين',
  'dashboard.hydration': 'شرب الماء',
  'dashboard.hydrationGoal': 'من {{goal}}',
  'dashboard.perBottle': '{{amount}} لكل قارورة',
  'dashboard.waterContainerMissing':
    'حدد قارورة الماء من الخادم عشان تفعّل الإضافة والخصم السريع.',
  'dashboard.decreaseWater': 'خصم قارورة ماء',
  'dashboard.increaseWater': 'إضافة قارورة ماء',
  'dashboard.selectContainer': 'اختيار {{container}}',

  'nutrient.protein': 'البروتين',
  'nutrient.carbs': 'الكربوهيدرات',
  'nutrient.netCarbs': 'صافي الكربوهيدرات',
  'nutrient.fat': 'الدهون',
  'nutrient.dietary_fiber': 'الألياف',
  'nutrient.sugars': 'السكريات',
  'nutrient.saturatedFat': 'الدهون المشبعة',
  'nutrient.transFat': 'الدهون المتحولة',
  'nutrient.cholesterol': 'الكوليسترول',
  'nutrient.sodium': 'الصوديوم',
  'nutrient.potassium': 'البوتاسيوم',
  'nutrient.calcium': 'الكالسيوم',
  'nutrient.iron': 'الحديد',
  'nutrient.vitaminA': 'فيتامين أ',
  'nutrient.vitaminC': 'فيتامين ج',
  'nutrient.totalCarbs': 'إجمالي الكربوهيدرات',

  'nutrition.calories': 'سعرة',
  'nutrition.goalPercent': '{{percent}}٪ من الهدف',
  'nutrition.showMore': 'عرض عناصر أكثر ▾',
  'nutrition.showLess': 'عرض عناصر أقل ▴',
  'nutrition.showMoreAccessibility': 'عرض عناصر غذائية أكثر',
  'nutrition.showLessAccessibility': 'عرض عناصر غذائية أقل',
  'nutrition.verifiedSource': 'بيانات موثّقة من المصدر',

  'charts.steps': 'الخطوات',
  'charts.pressSteps': 'اضغط على عمود عشان تشوف التفاصيل',
  'charts.stepsTooltip': '{{steps}} خطوة — {{date}}',
  'charts.loading': 'جاري التحميل…',
  'charts.stepsError': 'ما قدرنا نحمّل بيانات الخطوات',
  'charts.stepsEmpty': 'ما فيه بيانات خطوات لهالفترة',
  'charts.weight': 'الوزن',
  'charts.pressWeight': 'اضغط على الخط عشان تشوف التفاصيل',
  'charts.weightTooltip': '{{weight}} — {{date}}',
  'charts.weightError': 'ما قدرنا نحمّل بيانات الوزن',

  'measurement.weight': 'الوزن',
  'measurement.bodyFat': 'دهون الجسم',
  'measurement.height': 'الطول',
  'measurement.neck': 'الرقبة',
  'measurement.waist': 'الخصر',
  'measurement.hips': 'الأرداف',
  'measurement.steps': 'الخطوات',

  'mealType.breakfast': 'الفطور',
  'mealType.lunch': 'الغداء',
  'mealType.dinner': 'العشاء',
  'mealType.snacks': 'سناك',
  'mealType.other': 'أخرى',

  'units.calorie': 'سعرة',
  'units.minute': 'دقيقة',
  'units.g': 'غ',
  'units.mg': 'ملجم',
  'units.mcg': 'ميكروغرام',
  'units.kg': 'كجم',
  'units.lb': 'رطل',
  'units.minuteShort': 'د',
  'units.secondShort': 'ث',
  'units.meterShort': 'م',
  'units.beatsPerMinute': 'نبضة/دقيقة',
  'units.stepsPerMinute': 'خطوة/دقيقة',
  'units.stone': 'ستون',
  'units.ml': 'مل',
  'units.l': 'لتر',
  'units.cm': 'سم',
  'units.in': 'بوصة',
  'units.ft': 'قدم',
  'units.km': 'كم',
  'units.mi': 'ميل',
  'units.cup': 'كوب',
  'units.tbsp': 'ملعقة كبيرة',
  'units.tsp': 'ملعقة صغيرة',
  'units.oz': 'أونصة',
  'units.flOz': 'أونصة سائلة',
  'units.serving': 'حصة',
  'units.portion': 'كمية',
  'units.piece': 'قطعة',
  'units.slice': 'شريحة',
  'units.can': 'علبة',
  'units.bottle': 'قارورة',
  'units.packet': 'ظرف',
  'units.bag': 'كيس',
  'units.bowl': 'زبدية',
  'units.plate': 'صحن',
  'units.handful': 'حفنة',
  'units.scoop': 'سكوب',
  'units.bar': 'لوح',
  'units.stick': 'عود',
  'units.whole': 'كامل',
  'units.small': 'صغير',
  'units.medium': 'متوسط',
  'units.large': 'كبير',
  'units.extraLarge': 'كبير جدًا',
  'units.unit': 'وحدة',

  'screens.dashboard': 'الرئيسية',
  'screens.diary': 'اليوميات',
  'screens.library': 'المكتبة',
  'screens.settings': 'الإعدادات',
  'screens.foodsLibrary': 'الأصناف الغذائية',
  'screens.mealsLibrary': 'الوجبات',
  'screens.exercisesLibrary': 'التمارين',
  'screens.workoutPresetsLibrary': 'قوالب التمرين',
  'screens.foodDetails': 'تفاصيل الصنف',
  'screens.mealDetails': 'تفاصيل الوجبة',
  'screens.exerciseDetails': 'تفاصيل التمرين',
  'screens.workoutPresetDetails': 'تفاصيل قالب التمرين',
  'screens.foodSearch': 'البحث عن صنف',
  'screens.addFood': 'إضافة صنف',
  'screens.editFood': 'تعديل الصنف',
  'screens.adjustNutrition': 'تعديل القيم الغذائية',
  'screens.editBarcodes': 'تعديل الباركود',
  'screens.addExercise': 'إضافة تمرين',
  'screens.editExercise': 'تعديل التمرين',
  'screens.addWorkoutPreset': 'قالب تمرين جديد',
  'screens.editWorkoutPreset': 'تعديل قالب التمرين',
  'screens.scanFood': 'مسح منتج',
  'screens.foodPhoto': 'تصوير الوجبة',
  'screens.addMeal': 'إضافة وجبة',
  'screens.createMeal': 'وجبة جديدة',
  'screens.editMeal': 'تعديل الوجبة',
  'screens.foodEntry': 'تفاصيل التسجيل',
  'screens.editLoggedMeal': 'تعديل الوجبة المسجّلة',
  'screens.exerciseSearch': 'البحث عن تمرين',
  'screens.selectExercise': 'اختيار تمرين',
  'screens.presetSearch': 'اختيار قالب تمرين',
  'screens.startWorkout': 'بدء تمرين',
  'screens.logWorkout': 'تسجيل تمرين',
  'screens.logActivity': 'تسجيل نشاط',
  'screens.newWorkout': 'تمرين جديد',
  'screens.editWorkout': 'تعديل التمرين',
  'screens.newActivity': 'نشاط جديد',
  'screens.editActivity': 'تعديل النشاط',
  'screens.workout': 'تمرين',
  'screens.activity': 'نشاط',
  'screens.meal': 'وجبة',
  'screens.workoutDetails': 'تفاصيل التمرين',
  'screens.activeWorkout': 'التمرين الحالي',
  'screens.activityDetails': 'تفاصيل النشاط',
  'screens.fasting': 'الصيام',
  'screens.logs': 'السجل التقني',
  'screens.sync': 'مزامنة البيانات الصحية',
  'screens.measurements': 'إضافة القياسات',
  'screens.chat': 'اسأل سباركي',
  'screens.calorieSettings': 'إعدادات السعرات والأيض',
  'screens.foodSettings': 'إعدادات الأكل',
  'screens.dashboardSettings': 'إعدادات الرئيسية',
  'screens.serverSettings': 'إعدادات الخادم',
  'screens.passkeySettings': 'مفاتيح المرور',
  'screens.appSettings': 'إعدادات التطبيق',
  'screens.about': 'عن التطبيق',
  'screens.whatsNew': 'وش الجديد',
} as const;

export type MobileTranslationKey = keyof typeof ar;
