export const ar = {
  'common.cancel': 'إلغاء',
  'common.close': 'إغلاق',
  'common.continue': 'متابعة',
  'common.delete': 'حذف',
  'common.done': 'تم',
  'common.edit': 'تعديل',
  'common.error': 'صار خطأ',
  'common.goToSettings': 'الذهاب للإعدادات',
  'common.loading': 'جاري التحميل…',
  'common.notAvailable': 'غير متاح',
  'common.retry': 'حاول مرة ثانية',
  'common.save': 'حفظ',

  'tabs.dashboard': 'الرئيسية',
  'tabs.diary': 'اليوميات',
  'tabs.add': 'إضافة',
  'tabs.library': 'المكتبة',
  'tabs.settings': 'الإعدادات',

  'addSheet.food': 'صنف غذائي',
  'addSheet.exercise': 'تمرين',
  'addSheet.measurements': 'القياسات',
  'addSheet.scanFood': 'مسح منتج',
  'addSheet.workout': 'تمرين مباشر',
  'addSheet.workoutSubtitle': 'مجموعات وتكرارات مباشرة',
  'addSheet.activity': 'نشاط',
  'addSheet.activitySubtitle': 'مدة ومسافة',
  'addSheet.logWorkout': 'تسجيل تمرين سابق',
  'addSheet.logWorkoutSubtitle': 'مجموعات وتكرارات سابقة',
  'addSheet.askSparky': 'اسأل سباركي',
  'addSheet.syncHealth': 'مزامنة البيانات الصحية',

  'alerts.noServerTitle': 'ما فيه خادم متصل',
  'alerts.addExerciseNeedsServer': 'اربط خادمك من الإعدادات عشان تضيف تمرينًا.',
  'alerts.startWorkoutNeedsServer':
    'اربط خادمك من الإعدادات عشان تبدأ تمرينًا.',
  'alerts.draftTitle': 'عندك مسودة',
  'alerts.unsavedDraft': 'عندك مسودة {{activityType}} ما حفظتها. وش تبي تسوي؟',
  'alerts.workout': 'تمرين',
  'alerts.activity': 'نشاط',
  'alerts.resumeDraft': 'متابعة المسودة',
  'alerts.discardAndContinue': 'حذف المسودة والمتابعة',
  'alerts.healthUnavailableTitle': 'البيانات الصحية غير متاحة',
  'alerts.healthUnavailableDescription':
    'تعذر الوصول للبيانات الصحية. تأكد من الصلاحيات في الإعدادات.',

  'screens.dashboard': 'الرئيسية',
  'screens.diary': 'اليوميات',
  'screens.library': 'المكتبة',
  'screens.settings': 'الإعدادات',
  'screens.foodsLibrary': 'الأصناف الغذائية',
  'screens.mealsLibrary': 'الوجبات',
  'screens.exercisesLibrary': 'التمارين',
  'screens.workoutPresetsLibrary': 'قوالب التمرين',
  'screens.foodDetails': 'تفاصيل الصنف',
  'screens.mealDetails': 'تفاصيل الوجبة',
  'screens.exerciseDetails': 'تفاصيل التمرين',
  'screens.workoutPresetDetails': 'تفاصيل قالب التمرين',
  'screens.foodSearch': 'البحث عن صنف',
  'screens.addFood': 'إضافة صنف',
  'screens.editFood': 'تعديل الصنف',
  'screens.editBarcodes': 'تعديل الباركود',
  'screens.addExercise': 'إضافة تمرين',
  'screens.editExercise': 'تعديل التمرين',
  'screens.addWorkoutPreset': 'قالب تمرين جديد',
  'screens.editWorkoutPreset': 'تعديل قالب التمرين',
  'screens.scanFood': 'مسح منتج',
  'screens.foodPhoto': 'تصوير الوجبة',
  'screens.addMeal': 'إضافة وجبة',
  'screens.foodEntry': 'تفاصيل التسجيل',
  'screens.editLoggedMeal': 'تعديل الوجبة المسجّلة',
  'screens.exerciseSearch': 'البحث عن تمرين',
  'screens.presetSearch': 'اختيار قالب تمرين',
  'screens.logWorkout': 'تسجيل تمرين',
  'screens.logActivity': 'تسجيل نشاط',
  'screens.workoutDetails': 'تفاصيل التمرين',
  'screens.activeWorkout': 'التمرين الحالي',
  'screens.activityDetails': 'تفاصيل النشاط',
  'screens.fasting': 'الصيام',
  'screens.logs': 'السجل التقني',
  'screens.sync': 'مزامنة البيانات الصحية',
  'screens.measurements': 'إضافة القياسات',
  'screens.chat': 'اسأل سباركي',
  'screens.calorieSettings': 'إعدادات السعرات والأيض',
  'screens.foodSettings': 'إعدادات الأكل',
  'screens.dashboardSettings': 'إعدادات الرئيسية',
  'screens.serverSettings': 'إعدادات الخادم',
  'screens.passkeySettings': 'مفاتيح المرور',
  'screens.appSettings': 'إعدادات التطبيق',
  'screens.about': 'عن التطبيق',
  'screens.whatsNew': 'وش الجديد',
} as const;

export type MobileTranslationKey = keyof typeof ar;
