export const ar = {
  'common.back': 'رجوع',
  'common.cancel': 'إلغاء',
  'common.close': 'إغلاق',
  'common.continue': 'متابعة',
  'common.delete': 'حذف',
  'common.done': 'تم',
  'common.edit': 'تعديل',
  'common.error': 'صار خطأ',
  'common.goToSettings': 'الذهاب للإعدادات',
  'common.loading': 'جاري التحميل…',
  'common.notAvailable': 'غير متاح',
  'common.retry': 'حاول مرة ثانية',
  'common.save': 'حفظ',

  'tabs.dashboard': 'الرئيسية',
  'tabs.diary': 'اليوميات',
  'tabs.add': 'إضافة',
  'tabs.library': 'المكتبة',
  'tabs.settings': 'الإعدادات',

  'addSheet.food': 'صنف غذائي',
  'addSheet.exercise': 'تمرين',
  'addSheet.measurements': 'القياسات',
  'addSheet.scanFood': 'مسح منتج',
  'addSheet.workout': 'تمرين مباشر',
  'addSheet.workoutSubtitle': 'مجموعات وتكرارات مباشرة',
  'addSheet.activity': 'نشاط',
  'addSheet.activitySubtitle': 'مدة ومسافة',
  'addSheet.logWorkout': 'تسجيل تمرين سابق',
  'addSheet.logWorkoutSubtitle': 'مجموعات وتكرارات سابقة',
  'addSheet.askSparky': 'اسأل سباركي',
  'addSheet.syncHealth': 'مزامنة البيانات الصحية',

  'alerts.noServerTitle': 'ما فيه خادم متصل',
  'alerts.addExerciseNeedsServer': 'اربط خادمك من الإعدادات عشان تضيف تمرينًا.',
  'alerts.startWorkoutNeedsServer':
    'اربط خادمك من الإعدادات عشان تبدأ تمرينًا.',
  'alerts.draftTitle': 'عندك مسودة',
  'alerts.unsavedDraft': 'عندك مسودة {{activityType}} ما حفظتها. وش تبي تسوي؟',
  'alerts.workout': 'تمرين',
  'alerts.activity': 'نشاط',
  'alerts.resumeDraft': 'متابعة المسودة',
  'alerts.discardAndContinue': 'حذف المسودة والمتابعة',
  'alerts.healthUnavailableTitle': 'البيانات الصحية غير متاحة',
  'alerts.healthUnavailableDescription':
    'تعذر الوصول للبيانات الصحية. تأكد من الصلاحيات في الإعدادات.',

  'library.noServerTitle': 'ما فيه خادم مربوط',
  'library.noServerDescription':
    'اربط خادمك من الإعدادات عشان تشوف مكتبتك.',
  'library.loading': 'جاري تحميل المكتبة…',
  'library.create': 'إنشاء جديد',
  'library.browse': 'استعراض المكتبة',
  'library.food': 'صنف غذائي',
  'library.meal': 'وجبة',
  'library.exercise': 'تمرين',
  'library.workoutPreset': 'قالب تمرين',
  'library.manualEntry': 'إضافة يدوية',
  'library.groupFoods': 'اجمع أصنافك في وجبة',
  'library.exerciseRoutine': 'رتّب تمارينك واحفظها',
  'library.foods': 'الأصناف الغذائية',
  'library.meals': 'الوجبات',
  'library.exercises': 'التمارين',
  'library.workoutPresets': 'قوالب التمرين',
  'library.recentlyLogged': 'المسجّل مؤخرًا',
  'library.loadingRecent': 'جاري تحميل آخر تسجيلاتك…',
  'library.recentError': 'ما قدرنا نحمّل آخر تسجيلاتك.',
  'library.emptyTitle': 'ما سجّلت شي للحين',
  'library.emptyDescription':
    'الأصناف والوجبات والتمارين اللي تسجلها بتطلع هنا عشان توصل لها بسرعة.',

  'exerciseCategory.strength': 'قوة',
  'exerciseCategory.cardio': 'لياقة قلبية',
  'exerciseCategory.flexibility': 'مرونة',
  'exerciseCategory.balance': 'توازن',
  'exerciseCategory.mobility': 'حركة',
  'exerciseCategory.endurance': 'تحمّل',
  'exerciseCategory.sports': 'رياضة',
  'exerciseCategory.other': 'أخرى',

  'settings.server': 'الخادم',
  'settings.addServer': 'اضغط لإضافة خادم',
  'settings.lastSynced': 'آخر مزامنة {{time}}',
  'settings.serverAccessibilityConnected':
    'إعدادات الخادم. الاتصال شغال.',
  'settings.serverAccessibilityFailed':
    'إعدادات الخادم. تعذر الاتصال.',
  'settings.serverAccessibilityMissing':
    'إعدادات الخادم. ما فيه خادم مربوط.',
  'settings.shareDiagnostic': 'مشاركة تقرير التشخيص',
  'settings.diagnosticDescription':
    'يصدّر تقريرًا محليًا عن إصدار التطبيق وحالة المزامنة والسجل التقني. ما يشمل بياناتك الصحية أو أصنافك الغذائية، ولا يرسل أي شيء تلقائيًا.',
  'settings.shareFailed': 'ما قدرنا نجهّز التقرير. حاول مرة ثانية.',

  'diary.chooseDate': 'اختيار تاريخ اليوميات',
  'diary.previousDay': 'اليوم السابق',
  'diary.nextDay': 'اليوم التالي',
  'diary.openCalendar': 'اختيار التاريخ',
  'diary.noServerTitle': 'ما فيه خادم مربوط',
  'diary.noServerDescription':
    'اربط خادمك من الإعدادات عشان تشوف يومياتك.',
  'diary.loading': 'جاري تحميل يومياتك…',
  'diary.loadError': 'ما قدرنا نحمّل يومياتك',
  'diary.loadErrorDescription': 'تأكد من اتصالك وحاول مرة ثانية.',
  'diary.emptyDay': 'ما فيه تسجيلات لهاليوم',
  'diary.addFood': 'إضافة صنف غذائي',
  'diary.tapToAddFood': 'اضغط لإضافة صنف غذائي',
  'diary.nutritionBreakdown': 'تفاصيل تغذية {{meal}}',
  'diary.tapToAddExercise': 'اضغط لإضافة تمرين',
  'diary.addExercise': 'إضافة تمرين',
  'diary.exercise': 'التمارين',
  'diary.measurements': 'القياسات',
  'diary.editMeasurements': 'تعديل القياسات',
  'diary.unknownFood': 'صنف غير معروف',
  'diary.saving': 'جاري الحفظ…',
  'diary.viewDetails': 'عرض التفاصيل',
  'diary.adjustServing': 'تعديل الحصة',
  'diary.deleteFood': 'حذف التسجيل الغذائي',
  'diary.deleteExercise': 'حذف التمرين',

  'delete.failedTitle': 'ما قدرنا نحذف',
  'delete.foodEntryTitle': 'حذف التسجيل',
  'delete.foodEntryDescription': 'متأكد تبي تحذف هالتسجيل الغذائي؟',
  'delete.mealTitle': 'حذف الوجبة',
  'delete.mealDescription': 'متأكد تبي تحذف هالوجبة؟',
  'delete.workoutTitle': 'حذف التمرين؟',
  'delete.workoutDescription': 'بينحذف التمرين وكل تفاصيله نهائيًا.',
  'delete.activityTitle': 'حذف النشاط؟',
  'delete.activityDescription': 'بينحذف النشاط نهائيًا.',

  'workout.unknownExercise': 'تمرين غير معروف',
  'workout.exercise.one': 'تمرين واحد',
  'workout.exercise.two': 'تمرينين',
  'workout.exercise.few': '{{count}} تمارين',
  'workout.exercise.other': '{{count}} تمرين',
  'workout.set.one': 'مجموعة واحدة',
  'workout.set.two': 'مجموعتين',
  'workout.set.few': '{{count}} مجموعات',
  'workout.set.other': '{{count}} مجموعة',
  'workout.minute.one': 'دقيقة واحدة',
  'workout.minute.two': 'دقيقتين',
  'workout.minute.few': '{{count}} دقائق',
  'workout.minute.other': '{{count}} دقيقة',
  'workout.hour.one': 'ساعة',
  'workout.hour.two': 'ساعتين',
  'workout.hour.few': '{{count}} ساعات',
  'workout.hour.other': '{{count}} ساعة',

  'measurement.weight': 'الوزن',
  'measurement.bodyFat': 'دهون الجسم',
  'measurement.height': 'الطول',
  'measurement.neck': 'الرقبة',
  'measurement.waist': 'الخصر',
  'measurement.hips': 'الأرداف',
  'measurement.steps': 'الخطوات',

  'mealType.breakfast': 'الفطور',
  'mealType.lunch': 'الغداء',
  'mealType.dinner': 'العشاء',
  'mealType.snacks': 'سناك',
  'mealType.other': 'أخرى',

  'units.calorie': 'سعرة',
  'units.g': 'غ',
  'units.kg': 'كجم',
  'units.lb': 'رطل',
  'units.stone': 'ستون',
  'units.ml': 'مل',
  'units.l': 'لتر',
  'units.cm': 'سم',
  'units.in': 'بوصة',
  'units.ft': 'قدم',
  'units.km': 'كم',
  'units.mi': 'ميل',
  'units.cup': 'كوب',
  'units.tbsp': 'ملعقة كبيرة',
  'units.tsp': 'ملعقة صغيرة',
  'units.oz': 'أونصة',
  'units.serving': 'حصة',
  'units.portion': 'كمية',
  'units.piece': 'قطعة',
  'units.slice': 'شريحة',
  'units.can': 'علبة',
  'units.bottle': 'قارورة',
  'units.packet': 'ظرف',
  'units.bag': 'كيس',
  'units.bowl': 'زبدية',
  'units.plate': 'صحن',
  'units.handful': 'حفنة',
  'units.scoop': 'سكوب',
  'units.bar': 'لوح',
  'units.stick': 'عود',
  'units.whole': 'كامل',

  'screens.dashboard': 'الرئيسية',
  'screens.diary': 'اليوميات',
  'screens.library': 'المكتبة',
  'screens.settings': 'الإعدادات',
  'screens.foodsLibrary': 'الأصناف الغذائية',
  'screens.mealsLibrary': 'الوجبات',
  'screens.exercisesLibrary': 'التمارين',
  'screens.workoutPresetsLibrary': 'قوالب التمرين',
  'screens.foodDetails': 'تفاصيل الصنف',
  'screens.mealDetails': 'تفاصيل الوجبة',
  'screens.exerciseDetails': 'تفاصيل التمرين',
  'screens.workoutPresetDetails': 'تفاصيل قالب التمرين',
  'screens.foodSearch': 'البحث عن صنف',
  'screens.addFood': 'إضافة صنف',
  'screens.editFood': 'تعديل الصنف',
  'screens.adjustNutrition': 'تعديل القيم الغذائية',
  'screens.editBarcodes': 'تعديل الباركود',
  'screens.addExercise': 'إضافة تمرين',
  'screens.editExercise': 'تعديل التمرين',
  'screens.addWorkoutPreset': 'قالب تمرين جديد',
  'screens.editWorkoutPreset': 'تعديل قالب التمرين',
  'screens.scanFood': 'مسح منتج',
  'screens.foodPhoto': 'تصوير الوجبة',
  'screens.addMeal': 'إضافة وجبة',
  'screens.createMeal': 'وجبة جديدة',
  'screens.editMeal': 'تعديل الوجبة',
  'screens.foodEntry': 'تفاصيل التسجيل',
  'screens.editLoggedMeal': 'تعديل الوجبة المسجّلة',
  'screens.exerciseSearch': 'البحث عن تمرين',
  'screens.selectExercise': 'اختيار تمرين',
  'screens.presetSearch': 'اختيار قالب تمرين',
  'screens.startWorkout': 'بدء تمرين',
  'screens.logWorkout': 'تسجيل تمرين',
  'screens.logActivity': 'تسجيل نشاط',
  'screens.newWorkout': 'تمرين جديد',
  'screens.editWorkout': 'تعديل التمرين',
  'screens.newActivity': 'نشاط جديد',
  'screens.editActivity': 'تعديل النشاط',
  'screens.workout': 'تمرين',
  'screens.activity': 'نشاط',
  'screens.meal': 'وجبة',
  'screens.workoutDetails': 'تفاصيل التمرين',
  'screens.activeWorkout': 'التمرين الحالي',
  'screens.activityDetails': 'تفاصيل النشاط',
  'screens.fasting': 'الصيام',
  'screens.logs': 'السجل التقني',
  'screens.sync': 'مزامنة البيانات الصحية',
  'screens.measurements': 'إضافة القياسات',
  'screens.chat': 'اسأل سباركي',
  'screens.calorieSettings': 'إعدادات السعرات والأيض',
  'screens.foodSettings': 'إعدادات الأكل',
  'screens.dashboardSettings': 'إعدادات الرئيسية',
  'screens.serverSettings': 'إعدادات الخادم',
  'screens.passkeySettings': 'مفاتيح المرور',
  'screens.appSettings': 'إعدادات التطبيق',
  'screens.about': 'عن التطبيق',
  'screens.whatsNew': 'وش الجديد',
} as const;

export type MobileTranslationKey = keyof typeof ar;
