version: "3.9"

services:
  sparkyfitness-db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: ${SPARKY_FITNESS_DB_NAME}
      POSTGRES_USER: ${SPARKY_FITNESS_DB_USER}
      POSTGRES_PASSWORD: ${SPARKY_FITNESS_DB_PASSWORD}
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      - default # Use default bridge network

  sparkyfitness-frontend:
    image: codewithcj/sparkyfitness:latest # Use pre-built image
    ports:
      - "3004:3000" # Frontend port
    environment:
      NODE_ENV: production
      TZ: America/New_York # Set your timezone
      VITE_SPARKY_FITNESS_SERVER_HOST: sparkyfitness-server
      VITE_SPARKY_FITNESS_SERVER_PORT: $(SPARKY_FITNESS_SERVER_PORT)
    networks:
      - default # Use default bridge network
    restart: always
    depends_on:
      - sparkyfitness-db # Frontend depends on the database being available

  sparkyfitness-server:
    image: codewithcj/sparkyfitness_server:latest # Use pre-built image
    ports:
      - "${SPARKY_FITNESS_SERVER_PORT}:${SPARKY_FITNESS_SERVER_PORT}" # Backend port
    environment:
      SPARKY_FITNESS_SERVER_PORT: ${SPARKY_FITNESS_SERVER_PORT}
      SPARKY_FITNESS_LOG_LEVEL: ${SPARKY_FITNESS_LOG_LEVEL}
      SPARKY_FITNESS_DB_USER: ${SPARKY_FITNESS_DB_USER}
      SPARKY_FITNESS_DB_HOST: sparkyfitness-db # Use the service name 'sparkyfitness-db' for inter-container communication
      SPARKY_FITNESS_DB_NAME: ${SPARKY_FITNESS_DB_NAME}
      SPARKY_FITNESS_DB_PASSWORD: ${SPARKY_FITNESS_DB_PASSWORD}
      SPARKY_FITNESS_DB_PORT: 5432
      SPARKY_FITNESS_API_ENCRYPTION_KEY: ${SPARKY_FITNESS_API_ENCRYPTION_KEY}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - default # Use default bridge network
    restart: always
    depends_on:
      - sparkyfitness-db # Backend depends on the database being available

networks:
  default:
    driver: bridge
