version: "3.9"

services:
  sparkyfitness-frontend:
    image: codewithcj/sparkyfitness:latest
    ports:
      - "3004:3000"
    environment:
      NODE_ENV: production
      VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
      VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
      SUPABASE_PROJECT_REF: ${SUPABASE_PROJECT_REF}      
      VITE_SUPABASE_DB_PASSWORD: ${VITE_SUPABASE_DB_PASSWORD}
      #Below variable is optional. needed only to enable ChatBOT
      SUPABASE_ACCESS_TOKEN: ${SUPABASE_ACCESS_TOKEN}
      TZ: Etc/UTC
    networks:
      - sparky-fitness-ipv6-net
    restart: always

networks:
  sparky-fitness-ipv6-net:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: "2001:db8:3::/64"  
