// Generated by ts-to-zod
import { z } from "zod";

export const backupSettingsIdSchema = z.number().and(
  z.object({
    __brand: z.literal("public.backup_settings"),
  }),
);

export const backupSettingsSchema = z.object({
  id: backupSettingsIdSchema,
  backup_enabled: z.boolean(),
  backup_days: z.array(z.string()),
  backup_time: z.string(),
  retention_days: z.number(),
  last_backup_status: z.string().nullable(),
  last_backup_timestamp: z.date().nullable(),
  created_at: z.date().nullable(),
  updated_at: z.date().nullable(),
});

export const backupSettingsInitializerSchema = z.object({
  id: backupSettingsIdSchema.optional(),
  backup_enabled: z.boolean().optional(),
  backup_days: z.array(z.string()).optional(),
  backup_time: z.string().optional(),
  retention_days: z.number().optional(),
  last_backup_status: z.string().optional().nullable(),
  last_backup_timestamp: z.date().optional().nullable(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
});

export const backupSettingsMutatorSchema = z.object({
  id: backupSettingsIdSchema.optional(),
  backup_enabled: z.boolean().optional(),
  backup_days: z.array(z.string()).optional(),
  backup_time: z.string().optional(),
  retention_days: z.number().optional(),
  last_backup_status: z.string().optional().nullable(),
  last_backup_timestamp: z.date().optional().nullable(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
});

export type BackupSettings = z.infer<typeof backupSettingsSchema>;
export type BackupSettingsInitializer = z.infer<typeof backupSettingsInitializerSchema>;
export type BackupSettingsMutator = z.infer<typeof backupSettingsMutatorSchema>;
