// Generated by ts-to-zod
import { z } from "zod";

export type Goals = z.infer<typeof goalsSchema>;

export const goalsSchema = z.record(z.union([z.number(), z.undefined()])).and(
  z.object({
    calories: z.number(),
    protein: z.number(),
    carbs: z.number(),
    fat: z.number(),
    water_goal_ml: z.number(),
    dietary_fiber: z.number().optional(),
  }),
);

export type DayData = z.infer<typeof dayDataSchema>;

export const dayDataSchema = z.object({
  date: z.string(),
  calories: z.number(),
  protein: z.number(),
  carbs: z.number(),
  fat: z.number(),
  dietary_fiber: z.number(),
});
