export interface NutrientMetadata {
  id: string;
  label: string;
  defaultLabel: string;
  unit: string;
  color: string;
  decimals: number;
  group: 'macros' | 'fats' | 'minerals' | 'custom';
}

export const CENTRAL_NUTRIENT_CONFIG: Record<string, NutrientMetadata> = {
  calories: {
    id: 'calories',
    label: 'nutrition.calories',
    defaultLabel: 'Calories',
    unit: 'kcal',
    color: 'text-gray-900 dark:text-gray-100',
    decimals: 0,
    group: 'macros',
  },
  protein: {
    id: 'protein',
    label: 'nutrition.protein',
    defaultLabel: 'Protein',
    unit: 'g',
    color: 'text-blue-600',
    decimals: 1,
    group: 'macros',
  },
  carbs: {
    id: 'carbs',
    label: 'nutrition.carbohydrates',
    defaultLabel: 'Carbohydrates',
    unit: 'g',
    color: 'text-orange-600',
    decimals: 1,
    group: 'macros',
  },
  fat: {
    id: 'fat',
    label: 'nutrition.fat',
    defaultLabel: 'Fat',
    unit: 'g',
    color: 'text-yellow-600',
    decimals: 1,
    group: 'macros',
  },
  saturated_fat: {
    id: 'saturated_fat',
    label: 'nutrition.saturatedFat',
    defaultLabel: 'Saturated Fat',
    unit: 'g',
    color: 'text-red-500',
    decimals: 1,
    group: 'fats',
  },
  polyunsaturated_fat: {
    id: 'polyunsaturated_fat',
    label: 'nutrition.polyunsaturatedFat',
    defaultLabel: 'Polyunsaturated Fat',
    unit: 'g',
    color: 'text-lime-500',
    decimals: 1,
    group: 'fats',
  },
  monounsaturated_fat: {
    id: 'monounsaturated_fat',
    label: 'nutrition.monounsaturatedFat',
    defaultLabel: 'Monounsaturated Fat',
    unit: 'g',
    color: 'text-emerald-500',
    decimals: 1,
    group: 'fats',
  },
  trans_fat: {
    id: 'trans_fat',
    label: 'nutrition.transFat',
    defaultLabel: 'Trans Fat',
    unit: 'g',
    color: 'text-red-700',
    decimals: 1,
    group: 'fats',
  },
  cholesterol: {
    id: 'cholesterol',
    label: 'nutrition.cholesterol',
    defaultLabel: 'Cholesterol',
    unit: 'mg',
    color: 'text-indigo-500',
    decimals: 0,
    group: 'minerals',
  },
  sodium: {
    id: 'sodium',
    label: 'nutrition.sodium',
    defaultLabel: 'Sodium',
    unit: 'mg',
    color: 'text-purple-500',
    decimals: 0,
    group: 'minerals',
  },
  potassium: {
    id: 'potassium',
    label: 'nutrition.potassium',
    defaultLabel: 'Potassium',
    unit: 'mg',
    color: 'text-teal-500',
    decimals: 0,
    group: 'minerals',
  },
  dietary_fiber: {
    id: 'dietary_fiber',
    label: 'nutrition.dietaryFiber',
    defaultLabel: 'Dietary Fiber',
    unit: 'g',
    color: 'text-green-600',
    decimals: 1,
    group: 'minerals',
  },
  sugars: {
    id: 'sugars',
    label: 'nutrition.sugars',
    defaultLabel: 'Sugars',
    unit: 'g',
    color: 'text-pink-500',
    decimals: 1,
    group: 'minerals',
  },
  vitamin_a: {
    id: 'vitamin_a',
    label: 'nutrition.vitaminA',
    defaultLabel: 'Vitamin A',
    unit: 'µg',
    color: 'text-yellow-400',
    decimals: 0,
    group: 'minerals',
  },
  vitamin_c: {
    id: 'vitamin_c',
    label: 'nutrition.vitaminC',
    defaultLabel: 'Vitamin C',
    unit: 'mg',
    color: 'text-orange-400',
    decimals: 1,
    group: 'minerals',
  },
  calcium: {
    id: 'calcium',
    label: 'nutrition.calcium',
    defaultLabel: 'Calcium',
    unit: 'mg',
    color: 'text-blue-400',
    decimals: 0,
    group: 'minerals',
  },
  iron: {
    id: 'iron',
    label: 'nutrition.iron',
    defaultLabel: 'Iron',
    unit: 'mg',
    color: 'text-gray-500',
    decimals: 1,
    group: 'minerals',
  },
};
