FROM node:20-slim

WORKDIR /app/SparkyFitnessFrontend

# Install pnpm
RUN corepack enable && corepack prepare pnpm@10.30.3 --activate

COPY SparkyFitnessFrontend/package.json SparkyFitnessFrontend/pnpm-lock.yaml SparkyFitnessFrontend/pnpm-workspace.yaml ./
RUN pnpm install

EXPOSE 8080

CMD ["pnpm", "run", "dev", "--host", "0.0.0.0"]
