import { Platform } from 'react-native';

const ALL_HEALTH_METRICS = [
  { id: 'steps', label: 'Steps', stateKey: 'isStepsSyncEnabled', preferenceKey: 'syncStepsEnabled', recordType: 'Steps', unit: 'count', icon: require('../../assets/icons/steps.png'), permissions: [{ accessType: 'read', recordType: 'Steps' }, { accessType: 'write', recordType: 'Steps' }], type: 'step' },
  { id: 'calories', label: 'Active Calories', stateKey: 'isCaloriesSyncEnabled', preferenceKey: 'syncCaloriesEnabled', recordType: 'ActiveCaloriesBurned', unit: 'kcal', icon: require('../../assets/icons/calories.png'), permissions: [{ accessType: 'read', recordType: 'ActiveCaloriesBurned' }], type: 'Active Calories' },
  { id: 'totalCalories', label: 'Total Calories', stateKey: 'isTotalCaloriesSyncEnabled', preferenceKey: 'syncTotalCaloriesEnabled', recordType: 'TotalCaloriesBurned', unit: 'kcal', icon: require('../../assets/icons/calories.png'), permissions: [{ accessType: 'read', recordType: 'TotalCaloriesBurned' }], type: 'Active Calories' },
  { id: 'heartRate', label: 'Heart Rate', stateKey: 'isHeartRateSyncEnabled', preferenceKey: 'syncHeartRateEnabled', recordType: 'HeartRate', unit: 'bpm', icon: require('../../assets/icons/heart_rate.png'), permissions: [{ accessType: 'read', recordType: 'HeartRate' }], type: 'heart_rate' },
  { id: 'weight', label: 'Weight', stateKey: 'isWeightSyncEnabled', preferenceKey: 'syncWeightEnabled', recordType: 'Weight', unit: 'kg', icon: require('../../assets/icons/weight.png'), permissions: [{ accessType: 'read', recordType: 'Weight' }], type: 'weight' },
  { id: 'bloodPressure', label: 'Blood Pressure', stateKey: 'isBloodPressureSyncEnabled', preferenceKey: 'syncBloodPressureEnabled', recordType: 'BloodPressure', unit: 'mmHg', icon: require('../../assets/icons/blood_pressure.png'), permissions: [{ accessType: 'read', recordType: 'BloodPressure' }, { accessType: 'write', recordType: 'BloodPressure' }], type: 'blood_pressure' },
  { id: 'nutrition', label: 'Nutrition', stateKey: 'isNutritionSyncEnabled', preferenceKey: 'syncNutritionEnabled', recordType: 'Nutrition', unit: 'kcal', icon: require('../../assets/icons/nutrition.png'), permissions: [{ accessType: 'read', recordType: 'Nutrition' }], type: 'nutrition' },
  { id: 'sleepSession', label: 'Sleep Session', stateKey: 'isSleepSessionSyncEnabled', preferenceKey: 'syncSleepSessionEnabled', recordType: 'SleepSession', unit: 'min', icon: require('../../assets/icons/sleep_session.png'), permissions: [{ accessType: 'read', recordType: 'SleepSession' }], type: 'sleep_session' },
  { id: 'stress', label: 'Stress', stateKey: 'isStressSyncEnabled', preferenceKey: 'syncStressEnabled', recordType: 'Stress', unit: 'level', icon: require('../../assets/icons/stress.png'), permissions: [{ accessType: 'read', recordType: 'Stress' }], type: 'stress', platforms: ['ios'] },
  { id: 'basalBodyTemperature', label: 'Basal Body Temperature', stateKey: 'isBasalBodyTemperatureSyncEnabled', preferenceKey: 'syncBasalBodyTemperatureEnabled', recordType: 'BasalBodyTemperature', unit: 'celsius', icon: require('../../assets/icons/basal_body_temperature.png'), permissions: [{ accessType: 'read', recordType: 'BasalBodyTemperature' }], type: 'basal_body_temperature' },
  { id: 'basalMetabolicRate', label: 'Basal Metabolic Rate', stateKey: 'isBasalMetabolicRateSyncEnabled', preferenceKey: 'syncBasalMetabolicRateEnabled', recordType: 'BasalMetabolicRate', unit: 'kcal', icon: require('../../assets/icons/basal_metabolic_rate.png'), permissions: [{ accessType: 'read', recordType: 'BasalMetabolicRate' }], type: 'basal_metabolic_rate' },
  { id: 'bloodGlucose', label: 'Blood Glucose', stateKey: 'isBloodGlucoseSyncEnabled', preferenceKey: 'syncBloodGlucoseEnabled', recordType: 'BloodGlucose', unit: 'mmol/L', icon: require('../../assets/icons/blood_glucose.png'), permissions: [{ accessType: 'read', recordType: 'BloodGlucose' }], type: 'blood_glucose' },
  { id: 'bodyFat', label: 'Body Fat', stateKey: 'isBodyFatSyncEnabled', preferenceKey: 'syncBodyFatEnabled', recordType: 'BodyFat', unit: '%', icon: require('../../assets/icons/body_fat.png'), permissions: [{ accessType: 'read', recordType: 'BodyFat' }], type: 'body_fat' },
  { id: 'bodyTemperature', label: 'Body Temperature', stateKey: 'isBodyTemperatureSyncEnabled', preferenceKey: 'syncBodyTemperatureEnabled', recordType: 'BodyTemperature', unit: 'celsius', icon: require('../../assets/icons/body_temperature.png'), permissions: [{ accessType: 'read', recordType: 'BodyTemperature' }], type: 'body_temperature' },
  { id: 'boneMass', label: 'Bone Mass', stateKey: 'isBoneMassSyncEnabled', preferenceKey: 'syncBoneMassEnabled', recordType: 'BoneMass', unit: 'kg', icon: require('../../assets/icons/bone_mass.png'), permissions: [{ accessType: 'read', recordType: 'BoneMass' }], type: 'bone_mass' },
  { id: 'distance', label: 'Distance', stateKey: 'isDistanceSyncEnabled', preferenceKey: 'syncDistanceEnabled', recordType: 'Distance', unit: 'm', icon: require('../../assets/icons/distance.png'), permissions: [{ accessType: 'read', recordType: 'Distance' }], type: 'distance' },
  { id: 'elevationGained', label: 'Elevation Gained', stateKey: 'isElevationGainedSyncEnabled', preferenceKey: 'syncElevationGainedEnabled', recordType: 'ElevationGained', unit: 'm', icon: require('../../assets/icons/elevation_gained.png'), permissions: [{ accessType: 'read', recordType: 'ElevationGained' }], type: 'elevation_gained' },
  { id: 'exerciseSession', label: 'Exercise Session', stateKey: 'isExerciseSessionSyncEnabled', preferenceKey: 'syncExerciseSessionEnabled', recordType: 'ExerciseSession', unit: 'min', icon: require('../../assets/icons/exercise_session.png'), permissions: [{ accessType: 'read', recordType: 'ExerciseSession' }], type: 'exercise_session' },
  { id: 'floorsClimbed', label: 'Floors Climbed', stateKey: 'isFloorsClimbedSyncEnabled', preferenceKey: 'syncFloorsClimbedEnabled', recordType: 'FloorsClimbed', unit: 'count', icon: require('../../assets/icons/floors_climbed.png'), permissions: [{ accessType: 'read', recordType: 'FloorsClimbed' }], type: 'floors_climbed' },
  { id: 'height', label: 'Height', stateKey: 'isHeightSyncEnabled', preferenceKey: 'syncHeightEnabled', recordType: 'Height', unit: 'm', icon: require('../../assets/icons/height.png'), permissions: [{ accessType: 'read', recordType: 'Height' }], type: 'height' },
  { id: 'hydration', label: 'Hydration', stateKey: 'isHydrationSyncEnabled', preferenceKey: 'syncHydrationEnabled', recordType: 'Hydration', unit: 'L', icon: require('../../assets/icons/hydration.png'), permissions: [{ accessType: 'read', recordType: 'Hydration' }], type: 'hydration' },
  { id: 'leanBodyMass', label: 'Lean Body Mass', stateKey: 'isLeanBodyMassSyncEnabled', preferenceKey: 'syncLeanBodyMassEnabled', recordType: 'LeanBodyMass', unit: 'kg', icon: require('../../assets/icons/lean_body_mass.png'), permissions: [{ accessType: 'read', recordType: 'LeanBodyMass' }], type: 'lean_body_mass' },
  { id: 'oxygenSaturation', label: 'Oxygen Saturation', stateKey: 'isOxygenSaturationSyncEnabled', preferenceKey: 'syncOxygenSaturationEnabled', recordType: 'OxygenSaturation', unit: '%', icon: require('../../assets/icons/oxygen_saturation.png'), permissions: [{ accessType: 'read', recordType: 'OxygenSaturation' }], type: 'oxygen_saturation' },
  { id: 'power', label: 'Power', stateKey: 'isPowerSyncEnabled', preferenceKey: 'syncPowerEnabled', recordType: 'Power', unit: 'watts', icon: require('../../assets/icons/power.png'), permissions: [{ accessType: 'read', recordType: 'Power' }], type: 'power' },
  { id: 'respiratoryRate', label: 'Respiratory Rate', stateKey: 'isRespiratoryRateSyncEnabled', preferenceKey: 'syncRespiratoryRateEnabled', recordType: 'RespiratoryRate', unit: 'breaths/min', icon: require('../../assets/icons/respiratory_rate.png'), permissions: [{ accessType: 'read', recordType: 'RespiratoryRate' }], type: 'respiratory_rate' },
  { id: 'restingHeartRate', label: 'Resting Heart Rate', stateKey: 'isRestingHeartRateSyncEnabled', preferenceKey: 'syncRestingHeartRateEnabled', recordType: 'RestingHeartRate', unit: 'bpm', icon: require('../../assets/icons/resting_heart_rate.png'), permissions: [{ accessType: 'read', recordType: 'RestingHeartRate' }], type: 'resting_heart_rate' },
  { id: 'speed', label: 'Speed', stateKey: 'isSpeedSyncEnabled', preferenceKey: 'syncSpeedEnabled', recordType: 'Speed', unit: 'm/s', icon: require('../../assets/icons/speed.png'), permissions: [{ accessType: 'read', recordType: 'Speed' }], type: 'speed' },
  { id: 'vo2Max', label: 'VO2 Max', stateKey: 'isVo2MaxSyncEnabled', preferenceKey: 'syncVo2MaxEnabled', recordType: 'Vo2Max', unit: 'ml/min/kg', icon: require('../../assets/icons/vo2_max.png'), permissions: [{ accessType: 'read', recordType: 'Vo2Max' }], type: 'vo2_max' },
  { id: 'workout', label: 'Workout', stateKey: 'isWorkoutSyncEnabled', preferenceKey: 'syncWorkoutEnabled', recordType: 'Workout', unit: 'count', icon: require('../../assets/icons/workout.png'), permissions: [{ accessType: 'read', recordType: 'Workout' }], type: 'workout', platforms: ['ios'] },
  { id: 'wheelchairPushes', label: 'Wheelchair Pushes', stateKey: 'isWheelchairPushesSyncEnabled', preferenceKey: 'syncWheelchairPushesEnabled', recordType: 'WheelchairPushes', unit: 'count', icon: require('../../assets/icons/wheelchair_pushes.png'), permissions: [{ accessType: 'read', recordType: 'WheelchairPushes' }], type: 'wheelchair_pushes' },
  // ---- Added missing metrics ----
  // Android‑only metrics
  { id: 'cervicalMucus', label: 'Cervical Mucus', stateKey: 'isCervicalMucusSyncEnabled', preferenceKey: 'syncCervicalMucusEnabled', recordType: 'CervicalMucus', unit: 'level', icon: require('../../assets/icons/steps.png'), permissions: [{ accessType: 'read', recordType: 'CervicalMucus' }], type: 'cervical_mucus', platforms: ['android'], category: 'Reproductive' },
  { id: 'cyclingPedalingCadence', label: 'Cycling Pedaling Cadence', stateKey: 'isCyclingPedalingCadenceSyncEnabled', preferenceKey: 'syncCyclingPedalingCadenceEnabled', recordType: 'CyclingPedalingCadence', unit: 'rpm', icon: require('../../assets/icons/steps.png'), permissions: [{ accessType: 'read', recordType: 'CyclingPedalingCadence' }], type: 'cycling_pedaling_cadence', platforms: ['android'], category: 'Activity' },
  { id: 'exerciseRoute', label: 'Exercise Route', stateKey: 'isExerciseRouteSyncEnabled', preferenceKey: 'syncExerciseRouteEnabled', recordType: 'ExerciseRoute', unit: 'path', icon: require('../../assets/icons/steps.png'), permissions: [{ accessType: 'read', recordType: 'ExerciseRoute' }], type: 'exercise_route', platforms: ['android'], category: 'Activity' },
  { id: 'intermenstrualBleeding', label: 'Intermenstrual Bleeding', stateKey: 'isIntermenstrualBleedingSyncEnabled', preferenceKey: 'syncIntermenstrualBleedingEnabled', recordType: 'IntermenstrualBleeding', unit: 'level', icon: require('../../assets/icons/steps.png'), permissions: [{ accessType: 'read', recordType: 'IntermenstrualBleeding' }], type: 'intermenstrual_bleeding', platforms: ['android'], category: 'Reproductive' },
  { id: 'menstruationFlow', label: 'Menstruation Flow', stateKey: 'isMenstruationFlowSyncEnabled', preferenceKey: 'syncMenstruationFlowEnabled', recordType: 'MenstruationFlow', unit: 'level', icon: require('../../assets/icons/steps.png'), permissions: [{ accessType: 'read', recordType: 'MenstruationFlow' }], type: 'menstruation_flow', platforms: ['android'], category: 'Reproductive' },
  { id: 'menstruationPeriod', label: 'Menstruation Period', stateKey: 'isMenstruationPeriodSyncEnabled', preferenceKey: 'syncMenstruationPeriodEnabled', recordType: 'MenstruationPeriod', unit: 'date_range', icon: require('../../assets/icons/steps.png'), permissions: [{ accessType: 'read', recordType: 'MenstruationPeriod' }], type: 'menstruation_period', platforms: ['android'], category: 'Reproductive' },
  { id: 'ovulationTest', label: 'Ovulation Test', stateKey: 'isOvulationTestSyncEnabled', preferenceKey: 'syncOvulationTestEnabled', recordType: 'OvulationTest', unit: 'result', icon: require('../../assets/icons/steps.png'), permissions: [{ accessType: 'read', recordType: 'OvulationTest' }], type: 'ovulation_test', platforms: ['android'], category: 'Reproductive' },
  { id: 'stepsCadence', label: 'Steps Cadence', stateKey: 'isStepsCadenceSyncEnabled', preferenceKey: 'syncStepsCadenceEnabled', recordType: 'StepsCadence', unit: 'steps_per_second', icon: require('../../assets/icons/steps.png'), permissions: [{ accessType: 'read', recordType: 'StepsCadence' }], type: 'steps_cadence', platforms: ['android'], category: 'Activity' },
  { id: 'heartRateVariabilityRmssd', label: 'HRV (RMSSD)', stateKey: 'isHRVSyncEnabled', preferenceKey: 'syncHRVEnabled', recordType: 'HeartRateVariabilityRmssd', unit: 'ms', icon: require('../../assets/icons/steps.png'), permissions: [{ accessType: 'read', recordType: 'HeartRateVariabilityRmssd' }], type: 'hrv_rmssd', platforms: ['android'], category: 'Vitals' },
  { id: 'bloodAlcoholContent', label: 'Blood Alcohol Content', stateKey: 'isBloodAlcoholContentSyncEnabled', preferenceKey: 'syncBloodAlcoholContentEnabled', recordType: 'BloodAlcoholContent', unit: 'percent', icon: require('../../assets/icons/steps.png'), permissions: [{ accessType: 'read', recordType: 'BloodAlcoholContent' }], type: 'blood_alcohol_content', platforms: ['android'], category: 'Vitals' },
  { id: 'bloodOxygenSaturation', label: 'Blood Oxygen Saturation', stateKey: 'isBloodOxygenSaturationSyncEnabled', preferenceKey: 'syncBloodOxygenSaturationEnabled', recordType: 'BloodOxygenSaturation', unit: 'percent', icon: require('../../assets/icons/steps.png'), permissions: [{ accessType: 'read', recordType: 'BloodOxygenSaturation' }], type: 'blood_oxygen_saturation', platforms: ['android'], category: 'Vitals' },
  // iOS‑only metrics
  { id: 'bloodAlcoholContent', label: 'Blood Alcohol Content', stateKey: 'isBloodAlcoholContentSyncEnabled', preferenceKey: 'syncBloodAlcoholContentEnabled', recordType: 'BloodAlcoholContent', unit: 'percent', icon: require('../../assets/icons/steps.png'), permissions: [{ accessType: 'read', recordType: 'BloodAlcoholContent' }], type: 'blood_alcohol_content', platforms: ['ios'], category: 'Vitals' },
  { id: 'bloodOxygenSaturation', label: 'Blood Oxygen Saturation', stateKey: 'isBloodOxygenSaturationSyncEnabled', preferenceKey: 'syncBloodOxygenSaturationEnabled', recordType: 'BloodOxygenSaturation', unit: 'percent', icon: require('../../assets/icons/steps.png'), permissions: [{ accessType: 'read', recordType: 'BloodOxygenSaturation' }], type: 'blood_oxygen_saturation', platforms: ['ios'], category: 'Vitals' },
  { id: 'menstruationFlow', label: 'Menstruation Flow', stateKey: 'isMenstruationFlowSyncEnabled', preferenceKey: 'syncMenstruationFlowEnabled', recordType: 'MenstruationFlow', unit: 'level', icon: require('../../assets/icons/steps.png'), permissions: [{ accessType: 'read', recordType: 'MenstruationFlow' }], type: 'menstruation_flow', platforms: ['ios'], category: 'Reproductive' },
  { id: 'menstruationPeriod', label: 'Menstruation Period', stateKey: 'isMenstruationPeriodSyncEnabled', preferenceKey: 'syncMenstruationPeriodEnabled', recordType: 'MenstruationPeriod', unit: 'date_range', icon: require('../../assets/icons/steps.png'), permissions: [{ accessType: 'read', recordType: 'MenstruationPeriod' }], type: 'menstruation_period', platforms: ['ios'], category: 'Reproductive' },
  { id: 'ovulationTest', label: 'Ovulation Test', stateKey: 'isOvulationTestSyncEnabled', preferenceKey: 'syncOvulationTestEnabled', recordType: 'OvulationTest', unit: 'result', icon: require('../../assets/icons/steps.png'), permissions: [{ accessType: 'read', recordType: 'OvulationTest' }], type: 'ovulation_test', platforms: ['ios'], category: 'Reproductive' },
  { id: 'cervicalMucus', label: 'Cervical Mucus', stateKey: 'isCervicalMucusSyncEnabled', preferenceKey: 'syncCervicalMucusEnabled', recordType: 'CervicalMucus', unit: 'level', icon: require('../../assets/icons/steps.png'), permissions: [{ accessType: 'read', recordType: 'CervicalMucus' }], type: 'cervical_mucus', platforms: ['ios'], category: 'Reproductive' },
  { id: 'intermenstrualBleeding', label: 'Intermenstrual Bleeding', stateKey: 'isIntermenstrualBleedingSyncEnabled', preferenceKey: 'syncIntermenstrualBleedingEnabled', recordType: 'IntermenstrualBleeding', unit: 'level', icon: require('../../assets/icons/steps.png'), permissions: [{ accessType: 'read', recordType: 'IntermenstrualBleeding' }], type: 'intermenstrual_bleeding', platforms: ['ios'], category: 'Reproductive' },
  { id: 'stepsCadence', label: 'Steps Cadence', stateKey: 'isStepsCadenceSyncEnabled', preferenceKey: 'syncStepsCadenceEnabled', recordType: 'StepsCadence', unit: 'steps_per_second', icon: require('../../assets/icons/steps.png'), permissions: [{ accessType: 'read', recordType: 'StepsCadence' }], type: 'steps_cadence', platforms: ['ios'], category: 'Activity' },
  { id: 'heartRateVariabilityRmssd', label: 'HRV (RMSSD)', stateKey: 'isHRVSyncEnabled', preferenceKey: 'syncHRVEnabled', recordType: 'HeartRateVariabilityRmssd', unit: 'ms', icon: require('../../assets/icons/steps.png'), permissions: [{ accessType: 'read', recordType: 'HeartRateVariabilityRmssd' }], type: 'hrv_rmssd', platforms: ['ios'], category: 'Vitals' },
  { id: 'nutritionDietaryFatTotal', label: 'Dietary Fat Total', stateKey: 'isNutritionDietaryFatTotalSyncEnabled', preferenceKey: 'syncNutritionDietaryFatTotalEnabled', recordType: 'DietaryFatTotal', unit: 'g', icon: require('../../assets/icons/steps.png'), permissions: [{ accessType: 'read', recordType: 'DietaryFatTotal' }], type: 'nutrition', platforms: ['ios'], category: 'Nutrition' },
  { id: 'nutritionDietaryProtein', label: 'Dietary Protein', stateKey: 'isNutritionDietaryProteinSyncEnabled', preferenceKey: 'syncNutritionDietaryProteinEnabled', recordType: 'DietaryProtein', unit: 'g', icon: require('../../assets/icons/steps.png'), permissions: [{ accessType: 'read', recordType: 'DietaryProtein' }], type: 'nutrition', platforms: ['ios'], category: 'Nutrition' },
  { id: 'nutritionDietarySodium', label: 'Dietary Sodium', stateKey: 'isNutritionDietarySodiumSyncEnabled', preferenceKey: 'syncNutritionDietarySodiumEnabled', recordType: 'DietarySodium', unit: 'mg', icon: require('../../assets/icons/steps.png'), permissions: [{ accessType: 'read', recordType: 'DietarySodium' }], type: 'nutrition', platforms: ['ios'], category: 'Nutrition' },
  // Mobility / gait metrics (iOS only)
  { id: 'walkingSpeed', label: 'Walking Speed', stateKey: 'isWalkingSpeedSyncEnabled', preferenceKey: 'syncWalkingSpeedEnabled', recordType: 'WalkingSpeed', unit: 'm/s', icon: require('../../assets/icons/steps.png'), permissions: [{ accessType: 'read', recordType: 'WalkingSpeed' }], type: 'walking_speed', platforms: ['ios'], category: 'Mobility' },
  { id: 'walkingStepLength', label: 'Walking Step Length', stateKey: 'isWalkingStepLengthSyncEnabled', preferenceKey: 'syncWalkingStepLengthEnabled', recordType: 'WalkingStepLength', unit: 'cm', icon: require('../../assets/icons/steps.png'), permissions: [{ accessType: 'read', recordType: 'WalkingStepLength' }], type: 'walking_step_length', platforms: ['ios'], category: 'Mobility' },
  { id: 'walkingAsymmetryPercentage', label: 'Walking Asymmetry %', stateKey: 'isWalkingAsymmetrySyncEnabled', preferenceKey: 'syncWalkingAsymmetryEnabled', recordType: 'WalkingAsymmetryPercentage', unit: 'percent', icon: require('../../assets/icons/steps.png'), permissions: [{ accessType: 'read', recordType: 'WalkingAsymmetryPercentage' }], type: 'walking_asymmetry', platforms: ['ios'], category: 'Mobility' },
  { id: 'walkingDoubleSupportPercentage', label: 'Walking Double Support %', stateKey: 'isWalkingDoubleSupportSyncEnabled', preferenceKey: 'syncWalkingDoubleSupportEnabled', recordType: 'WalkingDoubleSupportPercentage', unit: 'percent', icon: require('../../assets/icons/steps.png'), permissions: [{ accessType: 'read', recordType: 'WalkingDoubleSupportPercentage' }], type: 'walking_double_support', platforms: ['ios'], category: 'Mobility' },
  // Running metrics (iOS only)
  { id: 'runningGroundContactTime', label: 'Running Ground Contact Time', stateKey: 'isRunningGroundContactSyncEnabled', preferenceKey: 'syncRunningGroundContactEnabled', recordType: 'RunningGroundContactTime', unit: 'ms', icon: require('../../assets/icons/steps.png'), permissions: [{ accessType: 'read', recordType: 'RunningGroundContactTime' }], type: 'running_ground_contact', platforms: ['ios'], category: 'Running' },
  { id: 'runningStrideLength', label: 'Running Stride Length', stateKey: 'isRunningStrideLengthSyncEnabled', preferenceKey: 'syncRunningStrideLengthEnabled', recordType: 'RunningStrideLength', unit: 'cm', icon: require('../../assets/icons/steps.png'), permissions: [{ accessType: 'read', recordType: 'RunningStrideLength' }], type: 'running_stride_length', platforms: ['ios'], category: 'Running' },
  { id: 'runningPower', label: 'Running Power', stateKey: 'isRunningPowerSyncEnabled', preferenceKey: 'syncRunningPowerEnabled', recordType: 'RunningPower', unit: 'watts', icon: require('../../assets/icons/steps.png'), permissions: [{ accessType: 'read', recordType: 'RunningPower' }], type: 'running_power', platforms: ['ios'], category: 'Running' },
  { id: 'runningVerticalOscillation', label: 'Running Vertical Oscillation', stateKey: 'isRunningVerticalOscillationSyncEnabled', preferenceKey: 'syncRunningVerticalOscillationEnabled', recordType: 'RunningVerticalOscillation', unit: 'cm', icon: require('../../assets/icons/steps.png'), permissions: [{ accessType: 'read', recordType: 'RunningVerticalOscillation' }], type: 'running_vertical_oscillation', platforms: ['ios'], category: 'Running' },
  { id: 'runningSpeed', label: 'Running Speed', stateKey: 'isRunningSpeedSyncEnabled', preferenceKey: 'syncRunningSpeedEnabled', recordType: 'RunningSpeed', unit: 'm/s', icon: require('../../assets/icons/steps.png'), permissions: [{ accessType: 'read', recordType: 'RunningSpeed' }], type: 'running_speed', platforms: ['ios'], category: 'Running' },
  // Cycling metrics (iOS only)
  { id: 'cyclingSpeed', label: 'Cycling Speed', stateKey: 'isCyclingSpeedSyncEnabled', preferenceKey: 'syncCyclingSpeedEnabled', recordType: 'CyclingSpeed', unit: 'm/s', icon: require('../../assets/icons/steps.png'), permissions: [{ accessType: 'read', recordType: 'CyclingSpeed' }], type: 'cycling_speed', platforms: ['ios'], category: 'Cycling' },
  { id: 'cyclingPower', label: 'Cycling Power', stateKey: 'isCyclingPowerSyncEnabled', preferenceKey: 'syncCyclingPowerEnabled', recordType: 'CyclingPower', unit: 'watts', icon: require('../../assets/icons/steps.png'), permissions: [{ accessType: 'read', recordType: 'CyclingPower' }], type: 'cycling_power', platforms: ['ios'], category: 'Cycling' },
  { id: 'cyclingCadence', label: 'Cycling Cadence', stateKey: 'isCyclingCadenceSyncEnabled', preferenceKey: 'syncCyclingCadenceEnabled', recordType: 'CyclingCadence', unit: 'rpm', icon: require('../../assets/icons/steps.png'), permissions: [{ accessType: 'read', recordType: 'CyclingCadence' }], type: 'cycling_cadence', platforms: ['ios'], category: 'Cycling' },
  { id: 'cyclingFunctionalThresholdPower', label: 'Cycling Functional Threshold Power', stateKey: 'isCyclingFTPsyncEnabled', preferenceKey: 'syncCyclingFTPEnabled', recordType: 'CyclingFunctionalThresholdPower', unit: 'watts', icon: require('../../assets/icons/steps.png'), permissions: [{ accessType: 'read', recordType: 'CyclingFunctionalThresholdPower' }], type: 'cycling_ftp', platforms: ['ios'], category: 'Cycling' },
  // Environmental / audio metrics (iOS only)
  { id: 'environmentalAudioExposure', label: 'Environmental Audio Exposure', stateKey: 'isEnvironmentalAudioExposureSyncEnabled', preferenceKey: 'syncEnvironmentalAudioExposureEnabled', recordType: 'EnvironmentalAudioExposure', unit: 'dB', icon: require('../../assets/icons/steps.png'), permissions: [{ accessType: 'read', recordType: 'EnvironmentalAudioExposure' }], type: 'environmental_audio_exposure', platforms: ['ios'], category: 'Environment' },
  { id: 'headphoneAudioExposure', label: 'Headphone Audio Exposure', stateKey: 'isHeadphoneAudioExposureSyncEnabled', preferenceKey: 'syncHeadphoneAudioExposureEnabled', recordType: 'HeadphoneAudioExposure', unit: 'dB', icon: require('../../assets/icons/steps.png'), permissions: [{ accessType: 'read', recordType: 'HeadphoneAudioExposure' }], type: 'headphone_audio_exposure', platforms: ['ios'], category: 'Environment' },
  // Apple‑specific metrics (iOS only)
  { id: 'appleMoveTime', label: 'Apple Move Time', stateKey: 'isAppleMoveTimeSyncEnabled', preferenceKey: 'syncAppleMoveTimeEnabled', recordType: 'AppleMoveTime', unit: 'seconds', icon: require('../../assets/icons/steps.png'), permissions: [{ accessType: 'read', recordType: 'AppleMoveTime' }], type: 'apple_move_time', platforms: ['ios'], category: 'Apple' },
  { id: 'appleExerciseTime', label: 'Apple Exercise Time', stateKey: 'isAppleExerciseTimeSyncEnabled', preferenceKey: 'syncAppleExerciseTimeEnabled', recordType: 'AppleExerciseTime', unit: 'seconds', icon: require('../../assets/icons/steps.png'), permissions: [{ accessType: 'read', recordType: 'AppleExerciseTime' }], type: 'apple_exercise_time', platforms: ['ios'], category: 'Apple' },
  { id: 'appleStandTime', label: 'Apple Stand Time', stateKey: 'isAppleStandTimeSyncEnabled', preferenceKey: 'syncAppleStandTimeEnabled', recordType: 'AppleStandTime', unit: 'seconds', icon: require('../../assets/icons/steps.png'), permissions: [{ accessType: 'read', recordType: 'AppleStandTime' }], type: 'apple_stand_time', platforms: ['ios'], category: 'Apple' },
  // End of added metrics
];

const HEALTH_METRICS = ALL_HEALTH_METRICS.filter(metric => {
  if (metric.platforms) {
    return metric.platforms.includes(Platform.OS);
  }
  return true;
});

export { HEALTH_METRICS };
