// Generated by ts-to-zod
import { z } from "zod";

const userIdSchema = z.any();

export const customCategoriesSchema = z.object({
  id: z.string(),
  user_id: z.string(),
  name: z.string(),
  measurement_type: z.string(),
  frequency: z.string(),
  created_at: z.date(),
  updated_at: z.date(),
  data_type: z.string().nullable(),
  created_by_user_id: userIdSchema.nullable(),
  updated_by_user_id: userIdSchema.nullable(),
  display_name: z.string().nullable(),
});

export const customCategoriesInitializerSchema = z.object({
  id: z.string().optional(),
  user_id: z.string(),
  name: z.string(),
  measurement_type: z.string(),
  frequency: z.string(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
  data_type: z.string().optional().nullable(),
  created_by_user_id: userIdSchema.optional().nullable(),
  updated_by_user_id: userIdSchema.optional().nullable(),
  display_name: z.string().optional().nullable(),
});

export const customCategoriesMutatorSchema = z.object({
  id: z.string().optional(),
  user_id: z.string().optional(),
  name: z.string().optional(),
  measurement_type: z.string().optional(),
  frequency: z.string().optional(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
  data_type: z.string().optional().nullable(),
  created_by_user_id: userIdSchema.optional().nullable(),
  updated_by_user_id: userIdSchema.optional().nullable(),
  display_name: z.string().optional().nullable(),
});

export type CustomCategories = z.infer<typeof customCategoriesSchema>;
export type CustomCategoriesInitializer = z.infer<typeof customCategoriesInitializerSchema>;
export type CustomCategoriesMutator = z.infer<typeof customCategoriesMutatorSchema>;
