import type { TFunction } from 'i18next';

const STANDARD_UNIT_KEYS: Readonly<Record<string, string>> = {
  g: 'units.gram',
  mg: 'units.milligram',
  µg: 'units.microgram',
  μg: 'units.microgram',
  mcg: 'units.microgram',
  kg: 'units.kilogram',
  st: 'units.stone',
  stone: 'units.stone',
  stones: 'units.stone',
  ml: 'units.milliliter',
  l: 'units.liter',
  liter: 'units.liter',
  litre: 'units.liter',
  oz: 'units.ounce',
  'fl oz': 'units.fluidOunce',
  kcal: 'units.kcal',
  kj: 'units.kJ',
  min: 'units.minuteShort',
  minute: 'units.minuteShort',
  minutes: 'units.minuteShort',
  cm: 'units.centimeter',
  km: 'units.kilometer',
  mi: 'units.mile',
  mile: 'units.mile',
  miles: 'units.mile',
  lb: 'units.pound',
  lbs: 'units.pound',
  in: 'units.inch',
  inch: 'units.inch',
  inches: 'units.inch',
  ft: 'units.foot',
  foot: 'units.foot',
  feet: 'units.foot',
  step: 'units.step',
  steps: 'units.step',
  year: 'units.year',
  years: 'units.year',
  bpm: 'units.bpm',
  '%': 'units.percent',
  serving: 'units.serving',
  servings: 'units.serving',
  cup: 'units.cup',
  cups: 'units.cup',
  tbsp: 'units.tablespoon',
  tablespoon: 'units.tablespoon',
  tablespoons: 'units.tablespoon',
  tsp: 'units.teaspoon',
  teaspoon: 'units.teaspoon',
  teaspoons: 'units.teaspoon',
  piece: 'units.piece',
  pieces: 'units.piece',
  slice: 'units.slice',
  slices: 'units.slice',
  portion: 'units.portion',
  portions: 'units.portion',
  can: 'units.can',
  cans: 'units.can',
  bottle: 'units.bottle',
  bottles: 'units.bottle',
  packet: 'units.packet',
  packets: 'units.packet',
  bag: 'units.bag',
  bags: 'units.bag',
  bowl: 'units.bowl',
  bowls: 'units.bowl',
  plate: 'units.plate',
  plates: 'units.plate',
  handful: 'units.handful',
  handfuls: 'units.handful',
  scoop: 'units.scoop',
  scoops: 'units.scoop',
  bar: 'units.bar',
  bars: 'units.bar',
  stick: 'units.stick',
  sticks: 'units.stick',
  whole: 'units.whole',
};

export const getLocalizedUnitLabel = (unit: string, t: TFunction): string => {
  const trimmedUnit = unit.trim();
  const translationKey = STANDARD_UNIT_KEYS[trimmedUnit.toLowerCase()];

  return translationKey ? t(translationKey) : trimmedUnit;
};
